// Synthetic component fixture. Run against a local staging dev server only.
// Real camera/device acceptance and authenticated preview remain separate.
import { execFileSync } from 'node:child_process';
import { copyFileSync,mkdirSync,rmSync } from 'node:fs';
import assert from 'node:assert/strict';
const base=process.argv[2]??'http://localhost:3111';
if(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(base)) throw new Error('Local server required');
const route=new URL('../../app/reception-check/',import.meta.url);
mkdirSync(route,{recursive:true});copyFileSync(new URL('./reception-fixture.tsx',import.meta.url),new URL('page.tsx',route));
const ab=(...args)=>execFileSync('npx',['--yes','agent-browser','--session','pace-p12',...args],{encoding:'utf8',timeout:60000});
const snap=()=>ab('snapshot','-i');
const click=name=>{ab('find','role','button','click','--name',name,'--exact');snap();};
const check=(code,label)=>{assert.match(ab('eval',`Boolean(${code})`),/true/,label);console.log(`PASS ${label}`);};
const wait=code=>{ab('wait','--fn',code);snap();};
const result=()=>wait('document.body.innerText.includes("Ultima operazione") && !document.body.innerText.includes("Operazione in corso")');
const open=()=>{ab('open',`${base}/reception-check`);snap();};
const count='JSON.parse(document.querySelector("[data-operations]").textContent).length';
try {
  open();
  click('Avvia fotocamera');click('QR singolo');result();
  check(`${count}===1 && document.body.innerText.includes("Ingresso registrato.")`,'single scan automatically enters');
  click('QR singolo');ab('wait','800');snap();check(`${count}===1`,'same visible QR does not repeat');
  click('QR famiglia');wait('document.querySelectorAll("input[name=presentSubjects]").length===2');
  check('document.querySelectorAll("input[name=presentSubjects]:checked").length===0','family never presumed present');
  ab('check',`input[value="22222222-2222-4222-8222-222222222222"]`);snap();click('Registra ingresso');result();
  check('document.body.innerText.includes("Presente dal") && document.body.innerText.includes("Ingresso non registrato")','partial family');
  click('Correzioni e annullamenti');
  ab('fill','input[type=text]','FAML');click('Verifica codice');wait('!!document.querySelector("input[name=confirmCorrection]")');
  check('document.querySelector("form:last-of-type button[type=submit]").disabled','correction requires confirmation');
  ab('check','input[value="11111111-1111-4111-8111-111111111111"]');ab('uncheck','input[value="22222222-2222-4222-8222-222222222222"]');ab('check','input[name=confirmCorrection]');snap();
  click('Correggi presenze');result();
  ab('select','select[name=operation]','cancel');snap();ab('fill','input[type=text]','FAML');click('Verifica codice');wait('!!document.querySelector("input[name=confirmCorrection]")');
  ab('check','input[value="11111111-1111-4111-8111-111111111111"]');ab('check','input[name=confirmCorrection]');snap();click('Annulla ingresso');result();
  check('!document.body.innerText.includes("Presente dal")','explicit cancellation');
  click('Torna agli ingressi');click('Avvia fotocamera');click('QR scuola');wait('document.querySelectorAll("input[type=number]").length===2');
  check('Array.from(document.querySelectorAll("input[type=number]")).every(e=>e.value==="")','school counts explicit');
  ab('fill','input[name=students]','18');ab('fill','input[name=companions]','2');snap();click('Registra ingresso');result();
  check('document.body.innerText.includes("18 studenti e 2 accompagnatori")','school aggregate response');
  ab('set','viewport','390','844');snap();
  check('document.documentElement.scrollWidth<=innerWidth','no mobile overflow');
  ab('screenshot','/tmp/pace-p12-mobile.png','--full');
  open();ab('select','main>label select','uncertain');snap();click('Codice manuale');ab('fill','input[type=text]','SOLO');click('Leggi codice e registra');
  wait('document.body.innerText.includes("Esito da verificare")');
  check('document.querySelector("input[type=text]").matches(":disabled")','uncertain outcome freezes original command');
  click('Riprova la stessa operazione');result();
  check('(()=>{const r=JSON.parse(document.querySelector("[data-requests]").textContent);return r.length===2&&r[0]===r[1]})()','retry retains exact request');
  ab('fill','input[type=text]','NOPE');click('Leggi codice e registra');wait('document.body.innerText.includes("Codice non valido")');
  check('!document.body.innerText.includes("Anna Bianchi")','invalid code clears identity');
  open();ab('select','main>label select','camera-denied');snap();click('Avvia fotocamera');wait('document.body.innerText.includes("Fotocamera non autorizzata")');
  ab('select','main>label select','normal');snap();click('Avvia fotocamera');click('Usa fotocamera anteriore');
  check('JSON.parse(document.querySelector("[data-camera]").textContent).facing==="user"','camera facing changed');
  click('Codice manuale');
  check('(()=>{const c=JSON.parse(document.querySelector("[data-camera]").textContent);return c.started===c.stopped})()','camera released in manual mode');
  ab('select','main>label select','forbidden');snap();ab('fill','input[type=text]','SOLO');click('Leggi codice e registra');wait('document.body.innerText.includes("Sessione scaduta o incarico")');
  check('document.querySelector("input[type=text]").matches(":disabled")','session expiry blocks operations');
  assert.equal(ab('errors').trim(),'');console.log('PASS no browser errors');
} finally {
  ab('close');rmSync(route,{recursive:true,force:true});
  rmSync(new URL('../../.next/dev/types/app/reception-check/',import.meta.url),{recursive:true,force:true});
}
