import type { SupportedLocale } from "../i18n/config";

const copy = {
  it: { title: "Il programma dell’incontro", intro: "Tre giorni ad Assisi per incontrarsi, dialogare e pregare per la pace.", discovery: "Scopri il programma e i panel", source: "Programma ufficiale", panels: "Scopri i panel", preview: "Anteprima riservata · La home pubblica resta invariata. Sono incluse le bozze del gestionale; iscrizioni e invio email sono disabilitati in questa anteprima.", draft: "Bozza", seats: "Posti disponibili per gli iscritti", incomplete: "Panel da completare nel gestionale", opening: "Assemblea d’inaugurazione — Pace disarmata e disarmante", prayers: "Preghiere per la pace", prayerPlace: "Luoghi diversi secondo le tradizioni religiose, nei pressi del Sacro Convento, Assisi", closing: "Cerimonia conclusiva" },
  en: { title: "The meeting programme", intro: "Three days in Assisi to meet, dialogue and pray for peace.", discovery: "Discover the programme and panels", source: "Official programme", panels: "Discover the panels", preview: "Private preview · The public home is unchanged. Dashboard drafts are included; registration and email submission are disabled in this preview.", draft: "Draft", seats: "Available seats for registered participants", incomplete: "Panels to complete in the dashboard", opening: "Opening assembly — Unarmed and disarming peace", prayers: "Prayers for peace", prayerPlace: "Different places according to religious traditions, near the Sacred Convent, Assisi", closing: "Closing ceremony" },
  fr: { title: "Le programme de la rencontre", intro: "Trois jours à Assise pour se rencontrer, dialoguer et prier pour la paix.", discovery: "Découvrez le programme et les panels", source: "Programme officiel", panels: "Découvrez les panels", preview: "Aperçu privé · La page publique reste inchangée. Les brouillons sont inclus ; inscriptions et envoi d’e-mails sont désactivés dans cet aperçu.", draft: "Brouillon", seats: "Places disponibles pour les inscrits", incomplete: "Panels à compléter dans le tableau de bord", opening: "Assemblée d’ouverture — Paix désarmée et désarmante", prayers: "Prières pour la paix", prayerPlace: "Différents lieux selon les traditions religieuses, près du Sacré Couvent, Assise", closing: "Cérémonie de clôture" },
  de: { title: "Das Programm des Treffens", intro: "Drei Tage in Assisi für Begegnung, Dialog und Gebet für den Frieden.", discovery: "Programm und Podien entdecken", source: "Offizielles Programm", panels: "Podien entdecken", preview: "Private Vorschau · Die öffentliche Startseite bleibt unverändert. Entwürfe sind enthalten; Anmeldung und E-Mail-Versand sind in dieser Vorschau deaktiviert.", draft: "Entwurf", seats: "Verfügbare Plätze für angemeldete Teilnehmende", incomplete: "Im Dashboard zu vervollständigende Podien", opening: "Eröffnungsversammlung — Unbewaffneter und entwaffnender Frieden", prayers: "Gebete für den Frieden", prayerPlace: "Verschiedene Orte je nach religiöser Tradition, in der Nähe des Sacro Convento, Assisi", closing: "Abschlusszeremonie" },
  es: { title: "El programa del encuentro", intro: "Tres días en Asís para encontrarse, dialogar y rezar por la paz.", discovery: "Descubre el programa y los paneles", source: "Programa oficial", panels: "Descubre los paneles", preview: "Vista previa privada · La página pública sigue igual. Se incluyen borradores; las inscripciones y el envío de correos están desactivados en esta vista previa.", draft: "Borrador", seats: "Plazas disponibles para los inscritos", incomplete: "Paneles por completar en el panel de gestión", opening: "Asamblea inaugural — Paz desarmada y desarmante", prayers: "Oraciones por la paz", prayerPlace: "Distintos lugares según las tradiciones religiosas, cerca del Sacro Convento, Asís", closing: "Ceremonia de clausura" },
  nl: { title: "Het programma van de ontmoeting", intro: "Drie dagen in Assisi voor ontmoeting, dialoog en gebed voor vrede.", discovery: "Ontdek het programma en de panels", source: "Officieel programma", panels: "Ontdek de panels", preview: "Privévoorbeeld · De openbare homepage blijft ongewijzigd. Concepten zijn inbegrepen; registratie en e-mailverzending zijn in dit voorbeeld uitgeschakeld.", draft: "Concept", seats: "Beschikbare plaatsen voor ingeschreven deelnemers", incomplete: "Panels om aan te vullen in het dashboard", opening: "Openingsbijeenkomst — Ongewapende en ontwapenende vrede", prayers: "Gebeden voor vrede", prayerPlace: "Verschillende plaatsen volgens de religieuze tradities, nabij het Sacro Convento, Assisi", closing: "Slotceremonie" },
  uk: { title: "Програма зустрічі", intro: "Три дні в Ассізі для зустрічей, діалогу та молитви за мир.", discovery: "Переглянути програму та панелі", source: "Офіційна програма", panels: "Переглянути панелі", preview: "Приватний перегляд · Публічна головна сторінка залишається незмінною. Чернетки включено; реєстрацію та надсилання листів у цьому перегляді вимкнено.", draft: "Чернетка", seats: "Доступні місця для зареєстрованих учасників", incomplete: "Панелі для доповнення в панелі керування", opening: "Відкриття зустрічі — Мир без зброї, що роззброює", prayers: "Молитви за мир", prayerPlace: "Різні місця відповідно до релігійних традицій поблизу Священного монастиря, Ассізі", closing: "Заключна церемонія" },
} satisfies Record<SupportedLocale, Record<string, string>>;

export function getEventProgramCopy(locale: SupportedLocale) { return copy[locale]; }
