import type { SupportedLocale } from "../i18n/config.ts";
const it = {
  title: "Posti alle cerimonie",
  intro:
    "Distribuisci ai membri i posti ricevuti dal manager. Ogni assegnazione utilizza la dotazione del gruppo, senza consumare due volte la capienza.",
  opening: "Inaugurazione",
  closing: "Cerimonia finale",
  choose: "Scegli una dotazione",
  allocation: "Dotazione",
  quantity: "Ricevuti",
  used: "Assegnati",
  remaining: "Disponibili",
  search: "Cerca nome o codice",
  assign: "Assegna un posto",
  noSeat: "Non serve un posto",
  noSeatState: "Nessun posto richiesto",
  child: "Minore accompagnato",
  childHelp:
    "Per ogni minore decidi caso per caso: assegna un posto oppure indica che non serve. La scelta del genitore non si applica ai figli.",
  pending: "Da assegnare",
  assigned: "Decisione già registrata",
  ineligible: "Presenza da verificare o non prevista",
  empty: "Nessuna dotazione disponibile.",
  none: "Nessuna persona corrisponde alla ricerca.",
  nominees: "Assegnazioni e scelte registrate",
  review:
    "Da rivedere: gruppo, iscrizione, minore o date sono cambiati. Il posto resta impegnato fino alla revoca o al trasferimento.",
  revoke: "Revoca o annulla la scelta",
  confirm: "Conferma revoca",
  move: "Trasferisci a un’altra dotazione",
  confirmMove: "Conferma trasferimento",
  refresh: "Aggiorna disponibilità",
  loading: "Operazione in corso…",
  saved: "Modifica salvata.",
  personalIntro:
    "Qui trovi i posti assegnati a te e ai figli accompagnati e le eventuali scelte senza posto. Non sono prenotazioni da effettuare né conferme di ingresso.",
  personalEmpty: "Non risultano ancora assegnazioni o scelte per le cerimonie.",
  back: "Torna alla tua area",
  readOnly: "Sola lettura",
  failure: "Impossibile caricare tutti i dati. Riprova.",
  conflict: "La dotazione è cambiata. Aggiorna e verifica prima di riprovare.",
  capacity: "La dotazione non ha posti sufficienti.",
  duplicate:
    "Questa persona ha già un posto o una scelta registrata per la cerimonia.",
  forbidden: "Non hai i permessi per questa operazione.",
  invalid: "Controlla la persona e la dotazione selezionate.",
  retry: "Riprova la stessa operazione",
  unavailable:
    "Esito non confermato. Aggiorna per verificare oppure riprova la stessa operazione.",
  unconfigured: "La configurazione non è ancora validata.",
  revokeHelp:
    "Un posto di gruppo torna disponibile nella stessa dotazione; revocare una scelta senza posto non cambia il residuo. Un posto assegnato direttamente dal manager viene liberato nella quota.",
  direct: "Assegnazione diretta",
  previous: "Precedenti",
  next: "Successivi",
};
type Copy = typeof it;
export const DISTRIBUTION_COPY: Record<SupportedLocale, Copy> = {
  it,
  en: {
    title: "Ceremony seats",
    intro:
      "Allocate the seats received from the manager to group members. Each assignment uses the group allowance without counting venue capacity twice.",
    opening: "Opening ceremony",
    closing: "Closing ceremony",
    choose: "Choose an allowance",
    allocation: "Allowance",
    quantity: "Received",
    used: "Assigned",
    remaining: "Available",
    search: "Search name or code",
    assign: "Assign one seat",
    noSeat: "No seat needed",
    noSeatState: "No seat requested",
    child: "Accompanied child",
    childHelp:
      "Decide for each child individually: assign a seat or record that none is needed. The parent’s choice does not apply to the children.",
    pending: "Not assigned",
    assigned: "Decision already recorded",
    ineligible: "Attendance unknown or not expected",
    empty: "No allowances available.",
    none: "No matching people.",
    nominees: "Recorded assignments and choices",
    review:
      "Review needed: group, registration, child details or dates have changed. The seat remains occupied until revoked or moved.",
    revoke: "Revoke or clear the choice",
    confirm: "Confirm revocation",
    move: "Move to another allowance",
    confirmMove: "Confirm move",
    refresh: "Refresh availability",
    loading: "Working…",
    saved: "Changes saved.",
    personalIntro:
      "Seats assigned to you and your accompanied children, including any no-seat choices. These are not bookings to make or confirmations of entry.",
    personalEmpty: "No ceremony assignments or choices yet.",
    back: "Back to your dashboard",
    readOnly: "Read only",
    failure: "Could not load all data. Try again.",
    conflict: "The allowance has changed. Refresh and check before retrying.",
    capacity: "Not enough seats in this allowance.",
    duplicate:
      "This person already has a seat or a recorded choice for this ceremony.",
    forbidden: "You do not have permission for this action.",
    invalid: "Check the selected person and allowance.",
    retry: "Retry the same operation",
    unavailable:
      "Outcome unconfirmed. Refresh to check or retry the same action.",
    unconfigured: "The configuration has not been validated.",
    revokeHelp:
      "A group seat returns to the same allowance. Clearing a no-seat choice does not change availability. Revoking a direct manager assignment releases its quota seat.",
    direct: "Direct assignment",
    previous: "Previous",
    next: "Next",
  },
  fr: {
    title: "Places aux cérémonies",
    intro:
      "Attribuez aux membres les places reçues du responsable. Chaque attribution utilise le contingent du groupe, sans compter deux fois la capacité.",
    opening: "Cérémonie d’ouverture",
    closing: "Cérémonie de clôture",
    choose: "Choisir un contingent",
    allocation: "Contingent",
    quantity: "Reçues",
    used: "Attribuées",
    remaining: "Disponibles",
    search: "Rechercher un nom ou code",
    assign: "Attribuer une place",
    noSeat: "Pas de place nécessaire",
    noSeatState: "Aucune place demandée",
    child: "Enfant accompagné",
    childHelp:
      "Décidez pour chaque enfant : attribuez une place ou indiquez qu’elle n’est pas nécessaire. Le choix du parent ne s’applique pas aux enfants.",
    pending: "À attribuer",
    assigned: "Décision déjà enregistrée",
    ineligible: "Présence à vérifier ou non prévue",
    empty: "Aucun contingent disponible.",
    none: "Aucune personne correspondante.",
    nominees: "Attributions et choix enregistrés",
    review:
      "À revoir : groupe, inscription, enfant ou dates modifiés. La place reste occupée jusqu’à sa révocation ou son transfert.",
    revoke: "Révoquer ou annuler le choix",
    confirm: "Confirmer la révocation",
    move: "Transférer vers un autre contingent",
    confirmMove: "Confirmer le transfert",
    refresh: "Actualiser les disponibilités",
    loading: "Opération en cours…",
    saved: "Modification enregistrée.",
    personalIntro:
      "Places attribuées à vous et aux enfants accompagnés, ainsi que les choix sans place. Il ne s’agit ni de réservations à effectuer ni de confirmations d’entrée.",
    personalEmpty: "Aucune attribution ou décision pour les cérémonies.",
    back: "Retour à votre espace",
    readOnly: "Lecture seule",
    failure: "Impossible de charger toutes les données. Réessayez.",
    conflict:
      "Le contingent a changé. Actualisez et vérifiez avant de réessayer.",
    capacity: "Places insuffisantes dans ce contingent.",
    duplicate:
      "Cette personne a déjà une place ou un choix enregistré pour cette cérémonie.",
    forbidden: "Vous n’êtes pas autorisé à effectuer cette opération.",
    invalid: "Vérifiez la personne et le contingent sélectionnés.",
    retry: "Répéter la même opération",
    unavailable:
      "Résultat non confirmé. Actualisez pour vérifier ou répétez la même opération.",
    unconfigured: "La configuration n’est pas encore validée.",
    revokeHelp:
      "Une place de groupe redevient disponible dans le même contingent. Annuler un choix sans place ne change pas le solde. Une attribution directe révoquée libère une place du quota.",
    direct: "Attribution directe",
    previous: "Précédents",
    next: "Suivants",
  },
  de: {
    title: "Plätze bei den Zeremonien",
    intro:
      "Verteile die von der Leitung erhaltenen Plätze an Gruppenmitglieder. Jede Zuweisung nutzt das Gruppenkontingent, ohne die Saalkapazität doppelt zu zählen.",
    opening: "Eröffnungszeremonie",
    closing: "Abschlusszeremonie",
    choose: "Kontingent wählen",
    allocation: "Kontingent",
    quantity: "Erhalten",
    used: "Zugewiesen",
    remaining: "Verfügbar",
    search: "Name oder Code suchen",
    assign: "Einen Platz zuweisen",
    noSeat: "Kein Platz benötigt",
    noSeatState: "Kein Platz angefordert",
    child: "Begleitetes Kind",
    childHelp:
      "Entscheide für jedes Kind einzeln: einen Platz zuweisen oder angeben, dass keiner benötigt wird. Die Wahl der Eltern gilt nicht für die Kinder.",
    pending: "Noch nicht zugewiesen",
    assigned: "Entscheidung bereits erfasst",
    ineligible: "Anwesenheit ungeklärt oder nicht geplant",
    empty: "Keine Kontingente verfügbar.",
    none: "Keine passenden Personen.",
    nominees: "Erfasste Zuweisungen und Entscheidungen",
    review:
      "Prüfung nötig: Gruppe, Anmeldung, Kind oder Termine geändert. Der Platz bleibt bis zum Widerruf oder Transfer belegt.",
    revoke: "Widerrufen oder Entscheidung aufheben",
    confirm: "Widerruf bestätigen",
    move: "In ein anderes Kontingent übertragen",
    confirmMove: "Transfer bestätigen",
    refresh: "Verfügbarkeit aktualisieren",
    loading: "Wird verarbeitet…",
    saved: "Änderung gespeichert.",
    personalIntro:
      "Plätze für dich und deine begleiteten Kinder sowie Entscheidungen ohne Sitzplatz. Dies sind keine vorzunehmenden Buchungen oder Einlassbestätigungen.",
    personalEmpty:
      "Noch keine Zuweisungen oder Entscheidungen für die Zeremonien.",
    back: "Zurück zu deinem Bereich",
    readOnly: "Nur lesen",
    failure:
      "Die Daten konnten nicht vollständig geladen werden. Erneut versuchen.",
    conflict:
      "Das Kontingent wurde geändert. Vor einem neuen Versuch aktualisieren und prüfen.",
    capacity: "Nicht genügend Plätze in diesem Kontingent.",
    duplicate:
      "Diese Person hat bereits einen Platz oder eine Entscheidung für diese Zeremonie.",
    forbidden: "Keine Berechtigung für diese Aktion.",
    invalid: "Person und Kontingent prüfen.",
    retry: "Dieselbe Aktion wiederholen",
    unavailable:
      "Ergebnis unbestätigt. Zur Prüfung aktualisieren oder dieselbe Aktion wiederholen.",
    unconfigured: "Die Konfiguration ist noch nicht bestätigt.",
    revokeHelp:
      "Ein Gruppenplatz wird im gleichen Kontingent frei. Das Aufheben einer Entscheidung ohne Platz ändert den Restbestand nicht. Ein direkt zugewiesener Platz wird bei Widerruf in der Quote frei.",
    direct: "Direkte Zuweisung",
    previous: "Zurück",
    next: "Weiter",
  },
  es: {
    title: "Plazas en las ceremonias",
    intro:
      "Distribuye entre los miembros las plazas recibidas del responsable. Cada asignación utiliza el cupo del grupo sin contar dos veces la capacidad.",
    opening: "Ceremonia inaugural",
    closing: "Ceremonia de clausura",
    choose: "Elige un cupo",
    allocation: "Cupo",
    quantity: "Recibidas",
    used: "Asignadas",
    remaining: "Disponibles",
    search: "Buscar nombre o código",
    assign: "Asignar una plaza",
    noSeat: "No necesita plaza",
    noSeatState: "No se solicita plaza",
    child: "Menor acompañado",
    childHelp:
      "Decide para cada menor: asigna una plaza o indica que no la necesita. La elección del progenitor no se aplica a los hijos.",
    pending: "Pendiente de asignar",
    assigned: "Decisión ya registrada",
    ineligible: "Asistencia por verificar o no prevista",
    empty: "No hay cupos disponibles.",
    none: "No hay personas que coincidan.",
    nominees: "Asignaciones y decisiones registradas",
    review:
      "Revisar: han cambiado el grupo, la inscripción, el menor o las fechas. La plaza sigue ocupada hasta su revocación o traslado.",
    revoke: "Revocar o anular la decisión",
    confirm: "Confirmar revocación",
    move: "Trasladar a otro cupo",
    confirmMove: "Confirmar traslado",
    refresh: "Actualizar disponibilidad",
    loading: "Procesando…",
    saved: "Cambio guardado.",
    personalIntro:
      "Plazas asignadas a ti y a tus hijos acompañados, incluidas las decisiones sin plaza. No son reservas que debas hacer ni confirmaciones de entrada.",
    personalEmpty:
      "Todavía no hay asignaciones o decisiones para las ceremonias.",
    back: "Volver a tu área",
    readOnly: "Solo lectura",
    failure: "No se pudieron cargar todos los datos. Inténtalo de nuevo.",
    conflict: "El cupo ha cambiado. Actualiza y verifica antes de reintentar.",
    capacity: "No hay suficientes plazas en este cupo.",
    duplicate:
      "Esta persona ya tiene una plaza o una decisión registrada para esta ceremonia.",
    forbidden: "No tienes permiso para esta operación.",
    invalid: "Comprueba la persona y el cupo seleccionados.",
    retry: "Repetir la misma operación",
    unavailable:
      "Resultado sin confirmar. Actualiza para verificar o repite la misma operación.",
    unconfigured: "La configuración aún no está validada.",
    revokeHelp:
      "Una plaza de grupo vuelve al mismo cupo. Anular una decisión sin plaza no cambia el saldo. Revocar una asignación directa libera una plaza en la cuota.",
    direct: "Asignación directa",
    previous: "Anteriores",
    next: "Siguientes",
  },
  nl: {
    title: "Plaatsen bij de ceremonies",
    intro:
      "Verdeel de ontvangen plaatsen onder de groepsleden. Elke toewijzing gebruikt het groepscontingent zonder de capaciteit dubbel te tellen.",
    opening: "Openingsceremonie",
    closing: "Slotceremonie",
    choose: "Kies een contingent",
    allocation: "Contingent",
    quantity: "Ontvangen",
    used: "Toegewezen",
    remaining: "Beschikbaar",
    search: "Zoek naam of code",
    assign: "Eén plaats toewijzen",
    noSeat: "Geen plaats nodig",
    noSeatState: "Geen plaats aangevraagd",
    child: "Begeleid kind",
    childHelp:
      "Beslis per kind: wijs een plaats toe of geef aan dat geen plaats nodig is. De keuze voor de ouder geldt niet voor de kinderen.",
    pending: "Nog niet toegewezen",
    assigned: "Beslissing al vastgelegd",
    ineligible: "Aanwezigheid onbekend of niet verwacht",
    empty: "Geen contingenten beschikbaar.",
    none: "Geen overeenkomende personen.",
    nominees: "Vastgelegde toewijzingen en keuzes",
    review:
      "Controleren: groep, inschrijving, kindgegevens of datums zijn gewijzigd. De plaats blijft bezet tot intrekking of verplaatsing.",
    revoke: "Intrekken of keuze wissen",
    confirm: "Intrekking bevestigen",
    move: "Naar een ander contingent verplaatsen",
    confirmMove: "Verplaatsing bevestigen",
    refresh: "Beschikbaarheid vernieuwen",
    loading: "Bezig…",
    saved: "Wijziging opgeslagen.",
    personalIntro:
      "Plaatsen voor jou en je begeleide kinderen, inclusief keuzes zonder plaats. Dit zijn geen te maken boekingen of toegangsbevestigingen.",
    personalEmpty: "Nog geen toewijzingen of keuzes voor de ceremonies.",
    back: "Terug naar je overzicht",
    readOnly: "Alleen lezen",
    failure: "Niet alle gegevens konden worden geladen. Probeer opnieuw.",
    conflict:
      "Het contingent is gewijzigd. Vernieuw en controleer voordat je opnieuw probeert.",
    capacity: "Niet genoeg plaatsen in dit contingent.",
    duplicate: "Deze persoon heeft al een plaats of keuze voor deze ceremonie.",
    forbidden: "Je hebt geen toestemming voor deze actie.",
    invalid: "Controleer de gekozen persoon en het contingent.",
    retry: "Dezelfde actie opnieuw proberen",
    unavailable:
      "Uitkomst niet bevestigd. Vernieuw om te controleren of herhaal dezelfde actie.",
    unconfigured: "De configuratie is nog niet bevestigd.",
    revokeHelp:
      "Een groepsplaats komt vrij in hetzelfde contingent. Een keuze zonder plaats wissen verandert het saldo niet. Een directe toewijzing intrekken geeft een plaats in het quotum vrij.",
    direct: "Directe toewijzing",
    previous: "Vorige",
    next: "Volgende",
  },
  uk: {
    title: "Місця на церемоніях",
    intro:
      "Розподіліть отримані від менеджера місця між учасниками групи. Кожне призначення використовує ліміт групи без подвійного обліку місткості.",
    opening: "Церемонія відкриття",
    closing: "Церемонія закриття",
    choose: "Оберіть виділені місця",
    allocation: "Виділені місця",
    quantity: "Отримано",
    used: "Призначено",
    remaining: "Доступно",
    search: "Пошук за ім’ям або кодом",
    assign: "Призначити одне місце",
    noSeat: "Місце не потрібне",
    noSeatState: "Місце не запитується",
    child: "Дитина в супроводі",
    childHelp:
      "Вирішуйте для кожної дитини окремо: призначте місце або вкажіть, що воно не потрібне. Вибір для батьків не поширюється на дітей.",
    pending: "Ще не призначено",
    assigned: "Рішення вже збережено",
    ineligible: "Присутність невідома або не передбачається",
    empty: "Немає виділених місць.",
    none: "Немає відповідних осіб.",
    nominees: "Збережені призначення та рішення",
    review:
      "Потрібна перевірка: змінилися група, реєстрація, дитина або дати. Місце залишається зайнятим до скасування або перенесення.",
    revoke: "Скасувати призначення або рішення",
    confirm: "Підтвердити скасування",
    move: "Перенести до іншого ліміту",
    confirmMove: "Підтвердити перенесення",
    refresh: "Оновити доступність",
    loading: "Виконується…",
    saved: "Зміни збережено.",
    personalIntro:
      "Місця для вас і дітей у вашому супроводі, зокрема рішення без місця. Це не бронювання, які треба зробити, і не підтвердження входу.",
    personalEmpty: "Поки немає призначень або рішень для церемоній.",
    back: "Повернутися до свого кабінету",
    readOnly: "Лише перегляд",
    failure: "Не вдалося завантажити всі дані. Спробуйте ще раз.",
    conflict:
      "Виділені місця змінилися. Оновіть і перевірте перед повторною спробою.",
    capacity: "У цьому ліміті недостатньо місць.",
    duplicate: "Ця особа вже має місце або рішення для цієї церемонії.",
    forbidden: "У вас немає дозволу на цю дію.",
    invalid: "Перевірте обрану особу та ліміт.",
    retry: "Повторити ту саму дію",
    unavailable:
      "Результат не підтверджено. Оновіть для перевірки або повторіть ту саму дію.",
    unconfigured: "Конфігурацію ще не підтверджено.",
    revokeHelp:
      "Місце групи повертається до того самого ліміту. Скасування рішення без місця не змінює залишок. Скасування прямого призначення звільняє місце у квоті.",
    direct: "Пряме призначення",
    previous: "Попередні",
    next: "Наступні",
  },
};
