import type { SupportedLocale } from "../i18n/config.ts";
const it = {
  title: "Piantina e posti numerati",
  back: "Torna alle cerimonie",
  intro:
    "La seduta numerata completa il posto già assegnato. Non registra un ingresso.",
  empty: "Piantina non ancora pubblicata.",
  allocation: "Dotazione o assegnazione diretta",
  choose: "Seleziona",
  sector: "Settore",
  all: "Tutti",
  row: "Fila",
  number: "Posto",
  seatPending: "Seduta da assegnare",
  version: "Versione",
  free: "Libero",
  blocked: "Non utilizzabile",
  occupied: "Impegnato",
  own: "Nella dotazione scelta",
  named: "Assegnato alla persona",
  selected: "Selezionati",
  map: "Mappa",
  table: "Tabella accessibile",
  zoom: "Zoom",
  search: "Cerca fila o posto",
  reserve: "Riserva alla dotazione",
  release: "Libera le sedute selezionate",
  unname: "Togli la seduta alla persona",
  name: "Assegna la seduta alla persona",
  nominee: "Persona con posto assegnato",
  clear: "Annulla selezione",
  contiguous: "Seleziona posti contigui",
  count: "Numero di posti",
  noRun: "Non ci sono posti contigui disponibili in una stessa fila.",
  refresh: "Aggiorna disponibilità",
  retry: "Riprova la stessa operazione",
  saved: "Modifica salvata.",
  unavailable:
    "Esito non confermato. Ripeti la stessa operazione per verificarlo.",
  failure:
    "Impossibile caricare la disponibilità completa. Aggiorna prima di continuare.",
  conflict: "La situazione è cambiata. Aggiorna e verifica la selezione.",
  capacity:
    "Capienza o dotazione insufficienti. La piantina deve coprire tutte le quote e rispettare le capienze.",
  forbidden: "Non hai i permessi per questa operazione.",
  invalid: "Controlla i dati e la selezione.",
  ineligible: "Assegnazione da rivedere: verifica gruppo, date e persona.",
  unconfigured:
    "La configurazione deve essere validata e la piantina pubblicata.",
  seats_active:
    "Prima togli le sedute alle persone e liberale dalla dotazione. Nessuna assegnazione è stata cancellata.",
  readOnly: "Sola lettura",
  loading: "Operazione in corso…",
  print: "Stampa elenco posti",
  remaining: "Sedute ancora da riservare",
  pendingPeople: "Persone ancora senza seduta",
  confirm: "Conferma la rimozione delle sedute selezionate",
  cancel: "Annulla",
  review: "Da rivedere",
};
type Copy = { [K in keyof typeof it]: string };
const en: Copy = {
  title: "Seating map and numbered seats",
  back: "Back to ceremonies",
  intro:
    "A numbered seat completes an existing allocation. It does not record admission.",
  empty: "No seating map published yet.",
  allocation: "Group allowance or direct allocation",
  choose: "Select",
  sector: "Sector",
  all: "All",
  row: "Row",
  number: "Seat",
  seatPending: "Seat number pending",
  version: "Version",
  free: "Available",
  blocked: "Unavailable",
  occupied: "Reserved",
  own: "In selected allowance",
  named: "Assigned to a person",
  selected: "Selected",
  map: "Map",
  table: "Accessible table",
  zoom: "Zoom",
  search: "Find row or seat",
  reserve: "Reserve for allowance",
  release: "Release selected seats",
  unname: "Remove person’s seat",
  name: "Assign seat to person",
  nominee: "Person with an allocation",
  clear: "Clear selection",
  contiguous: "Select adjacent seats",
  count: "Number of seats",
  noRun: "No adjacent seats available in one row.",
  refresh: "Refresh availability",
  retry: "Retry the same operation",
  saved: "Change saved.",
  unavailable: "Outcome unconfirmed. Retry the same operation to check.",
  failure: "Unable to load complete availability. Refresh before continuing.",
  conflict: "Availability changed. Refresh and check your selection.",
  capacity:
    "Insufficient capacity or allowance. The map must cover all quotas within capacity.",
  forbidden: "You do not have permission.",
  invalid: "Check the details and selection.",
  ineligible: "Allocation needs review: check group, dates and person.",
  unconfigured: "Validate the configuration and publish the seating map first.",
  seats_active:
    "Remove seats from people and release them from the allowance first. No allocations were deleted.",
  readOnly: "Read only",
  loading: "Working…",
  print: "Print seat list",
  remaining: "Seats still to reserve",
  pendingPeople: "People awaiting a seat number",
  confirm: "Confirm removal of the selected seats",
  cancel: "Cancel",
  review: "Needs review",
};
const fr: Copy = {
  title: "Plan et places numérotées",
  back: "Retour aux cérémonies",
  intro:
    "La place numérotée complète une attribution existante. Elle ne valide pas une entrée.",
  empty: "Aucun plan publié.",
  allocation: "Dotation du groupe ou attribution directe",
  choose: "Choisir",
  sector: "Secteur",
  all: "Tous",
  row: "Rangée",
  number: "Place",
  seatPending: "Place à préciser",
  version: "Version",
  free: "Libre",
  blocked: "Inutilisable",
  occupied: "Réservée",
  own: "Dans la dotation choisie",
  named: "Attribuée à une personne",
  selected: "Sélectionnées",
  map: "Plan",
  table: "Tableau accessible",
  zoom: "Zoom",
  search: "Chercher une rangée ou place",
  reserve: "Réserver à la dotation",
  release: "Libérer les places choisies",
  unname: "Retirer la place de la personne",
  name: "Attribuer la place à la personne",
  nominee: "Personne avec attribution",
  clear: "Effacer la sélection",
  contiguous: "Sélectionner des places contiguës",
  count: "Nombre de places",
  noRun: "Aucune place contiguë disponible dans une même rangée.",
  refresh: "Actualiser les disponibilités",
  retry: "Réessayer la même opération",
  saved: "Modification enregistrée.",
  unavailable: "Résultat non confirmé. Réessayez la même opération.",
  failure:
    "Disponibilités complètes indisponibles. Actualisez avant de continuer.",
  conflict: "La situation a changé. Actualisez et vérifiez la sélection.",
  capacity:
    "Capacité ou dotation insuffisante. Le plan doit couvrir les quotas sans dépasser les capacités.",
  forbidden: "Vous n’avez pas cette autorisation.",
  invalid: "Vérifiez les données et la sélection.",
  ineligible: "Attribution à revoir : vérifiez groupe, dates et personne.",
  unconfigured: "Validez la configuration et publiez le plan.",
  seats_active:
    "Retirez d’abord les places aux personnes, puis libérez-les de la dotation. Aucune attribution supprimée.",
  readOnly: "Lecture seule",
  loading: "En cours…",
  print: "Imprimer la liste des places",
  remaining: "Places restant à réserver",
  pendingPeople: "Personnes sans numéro de place",
  confirm: "Confirmer le retrait des places sélectionnées",
  cancel: "Annuler",
  review: "À revoir",
};
const de: Copy = {
  title: "Sitzplan und nummerierte Plätze",
  back: "Zurück zu den Zeremonien",
  intro:
    "Ein nummerierter Sitz ergänzt eine bestehende Zuteilung. Er erfasst keinen Einlass.",
  empty: "Noch kein Sitzplan veröffentlicht.",
  allocation: "Gruppenkontingent oder direkte Zuteilung",
  choose: "Auswählen",
  sector: "Bereich",
  all: "Alle",
  row: "Reihe",
  number: "Sitz",
  seatPending: "Sitznummer noch offen",
  version: "Version",
  free: "Frei",
  blocked: "Nicht nutzbar",
  occupied: "Reserviert",
  own: "Im ausgewählten Kontingent",
  named: "Einer Person zugeteilt",
  selected: "Ausgewählt",
  map: "Sitzplan",
  table: "Barrierefreie Tabelle",
  zoom: "Zoom",
  search: "Reihe oder Sitz suchen",
  reserve: "Für Kontingent reservieren",
  release: "Ausgewählte Sitze freigeben",
  unname: "Sitz von Person lösen",
  name: "Sitz einer Person zuweisen",
  nominee: "Person mit Zuteilung",
  clear: "Auswahl aufheben",
  contiguous: "Benachbarte Sitze auswählen",
  count: "Anzahl der Sitze",
  noRun: "Keine benachbarten Sitze in einer Reihe verfügbar.",
  refresh: "Verfügbarkeit aktualisieren",
  retry: "Denselben Vorgang wiederholen",
  saved: "Änderung gespeichert.",
  unavailable: "Ergebnis unbestätigt. Denselben Vorgang wiederholen.",
  failure: "Vollständige Verfügbarkeit nicht abrufbar. Zuerst aktualisieren.",
  conflict:
    "Die Situation hat sich geändert. Aktualisieren und Auswahl prüfen.",
  capacity:
    "Kapazität oder Kontingent reicht nicht aus. Der Plan muss alle Quoten innerhalb der Kapazitäten abdecken.",
  forbidden: "Keine Berechtigung für diesen Vorgang.",
  invalid: "Daten und Auswahl prüfen.",
  ineligible: "Zuteilung prüfen: Gruppe, Daten und Person.",
  unconfigured: "Konfiguration bestätigen und Sitzplan veröffentlichen.",
  seats_active:
    "Zuerst Sitze von Personen lösen und aus dem Kontingent freigeben. Keine Zuteilung wurde gelöscht.",
  readOnly: "Nur Lesen",
  loading: "Wird bearbeitet…",
  print: "Sitzliste drucken",
  remaining: "Noch zu reservierende Sitze",
  pendingPeople: "Personen ohne Sitznummer",
  confirm: "Entfernung der ausgewählten Sitze bestätigen",
  cancel: "Abbrechen",
  review: "Zu prüfen",
};
const es: Copy = {
  title: "Plano y asientos numerados",
  back: "Volver a las ceremonias",
  intro:
    "El asiento numerado completa una asignación existente. No registra una entrada.",
  empty: "Plano aún no publicado.",
  allocation: "Cupo de grupo o asignación directa",
  choose: "Seleccionar",
  sector: "Sector",
  all: "Todos",
  row: "Fila",
  number: "Asiento",
  seatPending: "Asiento por asignar",
  version: "Versión",
  free: "Libre",
  blocked: "No utilizable",
  occupied: "Reservado",
  own: "En el cupo seleccionado",
  named: "Asignado a una persona",
  selected: "Seleccionados",
  map: "Plano",
  table: "Tabla accesible",
  zoom: "Zoom",
  search: "Buscar fila o asiento",
  reserve: "Reservar al cupo",
  release: "Liberar asientos seleccionados",
  unname: "Quitar asiento a la persona",
  name: "Asignar asiento a la persona",
  nominee: "Persona con asignación",
  clear: "Borrar selección",
  contiguous: "Seleccionar asientos contiguos",
  count: "Número de asientos",
  noRun: "No hay asientos contiguos disponibles en una misma fila.",
  refresh: "Actualizar disponibilidad",
  retry: "Repetir la misma operación",
  saved: "Cambio guardado.",
  unavailable: "Resultado sin confirmar. Repite la misma operación.",
  failure:
    "No se pudo cargar toda la disponibilidad. Actualiza antes de continuar.",
  conflict: "La situación ha cambiado. Actualiza y revisa la selección.",
  capacity:
    "Capacidad o cupo insuficiente. El plano debe cubrir las cuotas dentro de la capacidad.",
  forbidden: "No tienes permiso para esta operación.",
  invalid: "Revisa los datos y la selección.",
  ineligible: "Asignación por revisar: comprueba grupo, fechas y persona.",
  unconfigured: "Valida la configuración y publica el plano.",
  seats_active:
    "Primero quita los asientos a las personas y libéralos del cupo. No se eliminó ninguna asignación.",
  readOnly: "Solo lectura",
  loading: "En curso…",
  print: "Imprimir lista de asientos",
  remaining: "Asientos pendientes de reservar",
  pendingPeople: "Personas sin número de asiento",
  confirm: "Confirmar retirada de los asientos seleccionados",
  cancel: "Cancelar",
  review: "Por revisar",
};
const nl: Copy = {
  title: "Plattegrond en genummerde stoelen",
  back: "Terug naar ceremonies",
  intro:
    "Een genummerde stoel vult een bestaande toewijzing aan. Er wordt geen toegang geregistreerd.",
  empty: "Nog geen plattegrond gepubliceerd.",
  allocation: "Groepsquotum of directe toewijzing",
  choose: "Selecteren",
  sector: "Vak",
  all: "Alle",
  row: "Rij",
  number: "Stoel",
  seatPending: "Stoelnummer nog toe te wijzen",
  version: "Versie",
  free: "Vrij",
  blocked: "Niet bruikbaar",
  occupied: "Gereserveerd",
  own: "In gekozen quotum",
  named: "Aan persoon toegewezen",
  selected: "Geselecteerd",
  map: "Plattegrond",
  table: "Toegankelijke tabel",
  zoom: "Zoom",
  search: "Zoek rij of stoel",
  reserve: "Reserveer voor quotum",
  release: "Geselecteerde stoelen vrijgeven",
  unname: "Stoel van persoon losmaken",
  name: "Stoel aan persoon toewijzen",
  nominee: "Persoon met toewijzing",
  clear: "Selectie wissen",
  contiguous: "Aangrenzende stoelen selecteren",
  count: "Aantal stoelen",
  noRun: "Geen aangrenzende stoelen beschikbaar in één rij.",
  refresh: "Beschikbaarheid vernieuwen",
  retry: "Dezelfde handeling opnieuw proberen",
  saved: "Wijziging opgeslagen.",
  unavailable: "Uitkomst niet bevestigd. Probeer dezelfde handeling opnieuw.",
  failure:
    "Volledige beschikbaarheid niet geladen. Vernieuw voordat je verdergaat.",
  conflict: "De situatie is gewijzigd. Vernieuw en controleer de selectie.",
  capacity:
    "Onvoldoende capaciteit of quotum. De plattegrond moet alle quota binnen de capaciteit dekken.",
  forbidden: "Geen toestemming voor deze handeling.",
  invalid: "Controleer gegevens en selectie.",
  ineligible: "Toewijzing controleren: groep, datums en persoon.",
  unconfigured: "Valideer de configuratie en publiceer de plattegrond.",
  seats_active:
    "Maak eerst stoelen los van personen en geef ze vrij uit het quotum. Er zijn geen toewijzingen verwijderd.",
  readOnly: "Alleen lezen",
  loading: "Bezig…",
  print: "Stoelenlijst afdrukken",
  remaining: "Nog te reserveren stoelen",
  pendingPeople: "Personen zonder stoelnummer",
  confirm: "Verwijdering van geselecteerde stoelen bevestigen",
  cancel: "Annuleren",
  review: "Te controleren",
};
const uk: Copy = {
  title: "План і нумеровані місця",
  back: "Назад до церемоній",
  intro: "Нумероване місце доповнює наявне призначення. Воно не реєструє вхід.",
  empty: "План ще не опубліковано.",
  allocation: "Квота групи або пряме призначення",
  choose: "Вибрати",
  sector: "Сектор",
  all: "Усі",
  row: "Ряд",
  number: "Місце",
  seatPending: "Номер місця ще не призначено",
  version: "Версія",
  free: "Вільне",
  blocked: "Недоступне",
  occupied: "Зарезервоване",
  own: "У вибраній квоті",
  named: "Призначене людині",
  selected: "Вибрано",
  map: "План",
  table: "Доступна таблиця",
  zoom: "Масштаб",
  search: "Шукати ряд або місце",
  reserve: "Зарезервувати для квоти",
  release: "Звільнити вибрані місця",
  unname: "Зняти місце з людини",
  name: "Призначити місце людині",
  nominee: "Людина з призначенням",
  clear: "Скасувати вибір",
  contiguous: "Вибрати сусідні місця",
  count: "Кількість місць",
  noRun: "Немає вільних сусідніх місць в одному ряду.",
  refresh: "Оновити доступність",
  retry: "Повторити ту саму операцію",
  saved: "Зміни збережено.",
  unavailable: "Результат не підтверджено. Повторіть ту саму операцію.",
  failure: "Не вдалося завантажити всі дані. Оновіть перед продовженням.",
  conflict: "Ситуація змінилася. Оновіть і перевірте вибір.",
  capacity:
    "Недостатня місткість або квота. План має покривати всі квоти в межах місткості.",
  forbidden: "У вас немає дозволу.",
  invalid: "Перевірте дані та вибір.",
  ineligible: "Призначення потребує перевірки: група, дати та людина.",
  unconfigured: "Підтвердьте конфігурацію та опублікуйте план.",
  seats_active:
    "Спочатку зніміть місця з людей і звільніть їх із квоти. Призначення не видалено.",
  readOnly: "Лише перегляд",
  loading: "Виконується…",
  print: "Друкувати список місць",
  remaining: "Місця, які ще слід зарезервувати",
  pendingPeople: "Люди без номера місця",
  confirm: "Підтвердити зняття вибраних місць",
  cancel: "Скасувати",
  review: "Потребує перевірки",
};
export const SEAT_MAP_COPY: Record<SupportedLocale, Copy> = {
  it,
  en,
  fr,
  de,
  es,
  nl,
  uk,
};
