import type { SupportedLocale } from "@/lib/i18n/config";

const it = {
  delete: "Elimina gruppo", title: "Eliminare questo gruppo?", cancel: "Annulla", loading: "Verifica del gruppo…",
  confirm: "Confermo l’eliminazione definitiva", reload: "Verifica di nuovo", deleted: "Gruppo eliminato.",
  close: "Chiudi", currentLabel: "Iscrizioni che resteranno senza gruppo",
  impact: "Gli iscritti conserveranno iscrizione, dati, presenze e QR e risulteranno senza questo gruppo. I capogruppo conserveranno account e altri incarichi: sarà scollegato solo il ruolo su questo gruppo. I link del gruppo smetteranno di funzionare. L’eliminazione è definitiva e i collegamenti precedenti saranno conservati nell’audit.",
  childrenLabel: "Sottogruppi", assignmentsLabel: "Assegnazioni presenti o storiche", membershipsLabel: "Incarichi dei referenti", linksLabel: "Link di iscrizione", rulesLabel: "Regole di assegnazione",
  children: "Questo nodo contiene sottogruppi. Spostali da Modifica → Appartiene a, oppure elimina prima quelli vuoti.",
  forbidden: "Non hai il permesso di eliminare questo gruppo.", conflict: "Il gruppo è cambiato. Verifica di nuovo i dettagli prima di confermare.",
  missing: "Il gruppo non è più disponibile. Aggiorna l’elenco.", failed: "Non è stato possibile completare l’operazione. Verifica di nuovo lo stato del gruppo.",
};
type Copy = { [K in keyof typeof it]: string };
export const GROUP_DELETION_COPY: Record<SupportedLocale, Copy> = {
  it,
  en: { delete: "Delete group", title: "Delete this group?", cancel: "Cancel", loading: "Checking group…", confirm: "I confirm permanent deletion", reload: "Check again", deleted: "Group deleted.", close: "Close", currentLabel: "Registrations that will have no group", impact: "Participants keep their registrations, details, attendance and QR codes and will no longer belong to this group. Leaders keep their accounts and other assignments; only their role in this group is removed. Group links will stop working. Deletion is permanent; previous links are retained in the audit log.", childrenLabel: "Subgroups", assignmentsLabel: "Current or historical assignments", membershipsLabel: "Leader assignments", linksLabel: "Registration links", rulesLabel: "Assignment rules", children: "This node contains subgroups. Move them using Edit → Belongs to, or delete empty subgroups first.", forbidden: "You do not have permission to delete this group.", conflict: "The group has changed. Check the details again before confirming.", missing: "The group is no longer available. Refresh the list.", failed: "The operation could not be completed. Check the group’s status again." },
  fr: { delete: "Supprimer le groupe", title: "Supprimer ce groupe ?", cancel: "Annuler", loading: "Vérification du groupe…", confirm: "Je confirme la suppression définitive", reload: "Vérifier à nouveau", deleted: "Groupe supprimé.", close: "Fermer", currentLabel: "Inscriptions qui seront sans groupe", impact: "Les participants conservent leur inscription, leurs données, leurs présences et leur QR et ne seront plus liés à ce groupe. Les responsables conservent leurs comptes et leurs autres affectations ; seul leur rôle dans ce groupe est retiré. Les liens du groupe ne fonctionneront plus. La suppression est définitive ; les anciens liens sont conservés dans le journal d’audit.", childrenLabel: "Sous-groupes", assignmentsLabel: "Affectations actuelles ou historiques", membershipsLabel: "Affectations des responsables", linksLabel: "Liens d’inscription", rulesLabel: "Règles d’affectation", children: "Ce nœud contient des sous-groupes. Déplacez-les via Modifier → Appartient à, ou supprimez d’abord ceux qui sont vides.", forbidden: "Vous ne pouvez pas supprimer ce groupe.", conflict: "Le groupe a changé. Vérifiez à nouveau les détails avant de confirmer.", missing: "Le groupe n’est plus disponible. Actualisez la liste.", failed: "L’opération n’a pas pu être effectuée. Vérifiez à nouveau l’état du groupe." },
  de: { delete: "Gruppe löschen", title: "Diese Gruppe löschen?", cancel: "Abbrechen", loading: "Gruppe wird geprüft…", confirm: "Ich bestätige die endgültige Löschung", reload: "Erneut prüfen", deleted: "Gruppe gelöscht.", close: "Schließen", currentLabel: "Anmeldungen, die ohne Gruppe bleiben", impact: "Teilnehmende behalten ihre Anmeldung, Daten, Anwesenheiten und QR-Codes und gehören dieser Gruppe nicht mehr an. Verantwortliche behalten ihre Konten und anderen Zuordnungen; nur ihre Rolle in dieser Gruppe wird entfernt. Gruppenlinks funktionieren danach nicht mehr. Die Löschung ist endgültig; frühere Verknüpfungen bleiben im Auditprotokoll erhalten.", childrenLabel: "Untergruppen", assignmentsLabel: "Aktuelle oder frühere Zuordnungen", membershipsLabel: "Leitungszuordnungen", linksLabel: "Anmeldelinks", rulesLabel: "Zuordnungsregeln", children: "Dieser Knoten enthält Untergruppen. Verschiebe sie über Bearbeiten → Gehört zu oder lösche zuerst die leeren Untergruppen.", forbidden: "Du darfst diese Gruppe nicht löschen.", conflict: "Die Gruppe wurde geändert. Prüfe die Details vor der Bestätigung erneut.", missing: "Die Gruppe ist nicht mehr verfügbar. Aktualisiere die Liste.", failed: "Der Vorgang konnte nicht abgeschlossen werden. Prüfe den Status der Gruppe erneut." },
  es: { delete: "Eliminar grupo", title: "¿Eliminar este grupo?", cancel: "Cancelar", loading: "Comprobando grupo…", confirm: "Confirmo la eliminación definitiva", reload: "Comprobar de nuevo", deleted: "Grupo eliminado.", close: "Cerrar", currentLabel: "Inscripciones que quedarán sin grupo", impact: "Los participantes conservarán su inscripción, datos, asistencia y QR y dejarán de pertenecer a este grupo. Los responsables conservarán sus cuentas y otras asignaciones; solo se desvincula su rol en este grupo. Los enlaces del grupo dejarán de funcionar. La eliminación es definitiva; las vinculaciones anteriores se conservan en el registro de auditoría.", childrenLabel: "Subgrupos", assignmentsLabel: "Asignaciones actuales o históricas", membershipsLabel: "Asignaciones de responsables", linksLabel: "Enlaces de inscripción", rulesLabel: "Reglas de asignación", children: "Este nodo contiene subgrupos. Muévelos desde Editar → Pertenece a, o elimina primero los que estén vacíos.", forbidden: "No tienes permiso para eliminar este grupo.", conflict: "El grupo ha cambiado. Comprueba de nuevo los detalles antes de confirmar.", missing: "El grupo ya no está disponible. Actualiza la lista.", failed: "No se pudo completar la operación. Comprueba de nuevo el estado del grupo." },
  nl: { delete: "Groep verwijderen", title: "Deze groep verwijderen?", cancel: "Annuleren", loading: "Groep controleren…", confirm: "Ik bevestig de definitieve verwijdering", reload: "Opnieuw controleren", deleted: "Groep verwijderd.", close: "Sluiten", currentLabel: "Inschrijvingen die zonder groep blijven", impact: "Deelnemers behouden hun inschrijving, gegevens, aanwezigheid en QR-code en horen niet meer bij deze groep. Groepsleiders behouden hun accounts en andere toewijzingen; alleen hun rol in deze groep vervalt. Groepslinks werken niet meer. Verwijdering is definitief; eerdere koppelingen blijven bewaard in het auditlogboek.", childrenLabel: "Subgroepen", assignmentsLabel: "Huidige of eerdere toewijzingen", membershipsLabel: "Toewijzingen van groepsleiders", linksLabel: "Inschrijflinks", rulesLabel: "Toewijzingsregels", children: "Dit knooppunt bevat subgroepen. Verplaats ze via Bewerken → Behoort tot, of verwijder eerst de lege subgroepen.", forbidden: "Je mag deze groep niet verwijderen.", conflict: "De groep is gewijzigd. Controleer de details opnieuw voordat je bevestigt.", missing: "De groep is niet meer beschikbaar. Vernieuw de lijst.", failed: "De bewerking kon niet worden voltooid. Controleer de status van de groep opnieuw." },
  uk: { delete: "Видалити групу", title: "Видалити цю групу?", cancel: "Скасувати", loading: "Перевірка групи…", confirm: "Підтверджую остаточне видалення", reload: "Перевірити знову", deleted: "Групу видалено.", close: "Закрити", currentLabel: "Реєстрації, що залишаться без групи", impact: "Учасники збережуть реєстрацію, дані, відвідування та QR-коди й більше не належатимуть до цієї групи. Керівники збережуть облікові записи та інші призначення; буде скасовано лише роль у цій групі. Посилання групи перестануть працювати. Видалення остаточне; попередні зв’язки зберігаються в журналі аудиту.", childrenLabel: "Підгрупи", assignmentsLabel: "Поточні або попередні призначення", membershipsLabel: "Призначення керівників", linksLabel: "Посилання на реєстрацію", rulesLabel: "Правила призначення", children: "Цей вузол містить підгрупи. Перемістіть їх через Редагувати → Належить до або спочатку видаліть порожні підгрупи.", forbidden: "Ви не маєте дозволу видалити цю групу.", conflict: "Група змінилася. Перевірте дані знову перед підтвердженням.", missing: "Група більше недоступна. Оновіть список.", failed: "Не вдалося завершити операцію. Перевірте стан групи знову." },
};
