import type { SupportedLocale } from "../i18n/config.ts";
const it = {
  title: "Territorio per i suggerimenti", country: "Paese", city: "Città (facoltativa)", addCity: "Aggiungi un’altra città", removeCity: "Rimuovi città", chooseCity: "Seleziona una città",
  inherit: "Usa il territorio del nodo superiore", allCities: "Tutte le città del paese", other: "Altra città", cityName: "Nome della città",
  none: "Nessun territorio collegato: il gruppo non verrà suggerito in base al paese.",
  hint: "Collega il paese per proporre il gruppo a chi vi abita. Aggiungi una o più città per circoscrivere i suggerimenti a quelle città, quando riconosciute. Restano validi visibilità, iscrivibilità e fasce di età.",
  inherited: "Territorio ereditato", selectCountry: "Seleziona prima un paese", inactive: "non attivo",
  conflict: "Questi dati sono cambiati. Riapri la scheda del gruppo prima di salvare.",
  territoryError: "Il territorio non è coerente con il nodo superiore o con i sottogruppi. Controlla paese, città e gerarchia.",
};
export const GROUP_GEOGRAPHY_COPY: Record<SupportedLocale, typeof it> = {
  it,
  en: { title: "Location for group suggestions", country: "Country", city: "City (optional)", addCity: "Add another city", removeCity: "Remove city", chooseCity: "Select a city", inherit: "Use the parent node’s location", allCities: "All cities in the country", other: "Other city", cityName: "City name", none: "No location linked: this group will not be suggested by country.", hint: "Link a country to suggest the group to residents. Add one or more cities to limit suggestions to those cities, when recognized. Visibility, signup eligibility and age filters still apply.", inherited: "Inherited location", selectCountry: "Select a country first", inactive: "inactive", conflict: "These details have changed. Reopen the group before saving.", territoryError: "The location conflicts with the parent or child groups. Check the country, city and hierarchy." },
  fr: { title: "Territoire pour les suggestions", country: "Pays", city: "Ville (facultative)", addCity: "Ajouter une autre ville", removeCity: "Retirer la ville", chooseCity: "Sélectionnez une ville", inherit: "Utiliser le territoire du nœud parent", allCities: "Toutes les villes du pays", other: "Autre ville", cityName: "Nom de la ville", none: "Aucun territoire associé : le groupe ne sera pas proposé selon le pays.", hint: "Associez un pays pour proposer le groupe à ses habitants. Ajoutez une ou plusieurs villes pour limiter les suggestions à ces villes, lorsqu’elles sont reconnues. La visibilité, les inscriptions et les filtres d’âge restent applicables.", inherited: "Territoire hérité", selectCountry: "Sélectionnez d’abord un pays", inactive: "inactif", conflict: "Ces données ont changé. Rouvrez le groupe avant d’enregistrer.", territoryError: "Le territoire est incompatible avec le parent ou les sous-groupes. Vérifiez le pays, la ville et la hiérarchie." },
  de: { title: "Gebiet für Gruppenvorschläge", country: "Land", city: "Stadt (optional)", addCity: "Weitere Stadt hinzufügen", removeCity: "Stadt entfernen", chooseCity: "Stadt auswählen", inherit: "Gebiet des übergeordneten Knotens verwenden", allCities: "Alle Städte des Landes", other: "Andere Stadt", cityName: "Name der Stadt", none: "Kein Gebiet verknüpft: Die Gruppe wird nicht anhand des Landes vorgeschlagen.", hint: "Verknüpfen Sie ein Land, um die Gruppe dessen Einwohnern vorzuschlagen. Fügen Sie eine oder mehrere Städte hinzu, um die Vorschläge auf diese Städte zu beschränken, wenn sie erkannt werden. Sichtbarkeit, Anmeldbarkeit und Altersfilter gelten weiterhin.", inherited: "Geerbtes Gebiet", selectCountry: "Wählen Sie zuerst ein Land", inactive: "inaktiv", conflict: "Diese Daten wurden geändert. Öffnen Sie die Gruppe erneut, bevor Sie speichern.", territoryError: "Das Gebiet widerspricht dem übergeordneten Knoten oder den Untergruppen. Prüfen Sie Land, Stadt und Hierarchie." },
  es: { title: "Territorio para las sugerencias", country: "País", city: "Ciudad (opcional)", addCity: "Añadir otra ciudad", removeCity: "Eliminar ciudad", chooseCity: "Selecciona una ciudad", inherit: "Usar el territorio del nodo superior", allCities: "Todas las ciudades del país", other: "Otra ciudad", cityName: "Nombre de la ciudad", none: "Sin territorio vinculado: el grupo no se sugerirá según el país.", hint: "Vincula un país para sugerir el grupo a sus residentes. Añade una o varias ciudades para limitar las sugerencias a esas ciudades, cuando se reconozcan. Siguen aplicándose la visibilidad, la inscripción y los filtros de edad.", inherited: "Territorio heredado", selectCountry: "Selecciona primero un país", inactive: "inactivo", conflict: "Estos datos han cambiado. Vuelve a abrir el grupo antes de guardar.", territoryError: "El territorio no coincide con el nodo superior o los subgrupos. Revisa el país, la ciudad y la jerarquía." },
  nl: { title: "Gebied voor groepssuggesties", country: "Land", city: "Stad (optioneel)", addCity: "Nog een stad toevoegen", removeCity: "Stad verwijderen", chooseCity: "Selecteer een stad", inherit: "Gebruik het gebied van de bovenliggende node", allCities: "Alle steden in het land", other: "Andere stad", cityName: "Naam van de stad", none: "Geen gebied gekoppeld: de groep wordt niet op basis van het land voorgesteld.", hint: "Koppel een land om de groep aan inwoners voor te stellen. Voeg een of meer steden toe om suggesties tot die steden te beperken, wanneer ze worden herkend. Zichtbaarheid, inschrijfbaarheid en leeftijdsfilters blijven gelden.", inherited: "Overgenomen gebied", selectCountry: "Selecteer eerst een land", inactive: "inactief", conflict: "Deze gegevens zijn gewijzigd. Open de groep opnieuw voordat u opslaat.", territoryError: "Het gebied is niet verenigbaar met de bovenliggende node of subgroepen. Controleer land, stad en hiërarchie." },
  uk: { title: "Територія для рекомендацій груп", country: "Країна", city: "Місто (необов’язково)", addCity: "Додати ще одне місто", removeCity: "Видалити місто", chooseCity: "Виберіть місто", inherit: "Використовувати територію батьківського вузла", allCities: "Усі міста країни", other: "Інше місто", cityName: "Назва міста", none: "Територію не пов’язано: група не пропонуватиметься за країною.", hint: "Пов’яжіть країну, щоб пропонувати групу її мешканцям. Додайте одне або кілька міст, щоб обмежити рекомендації цими містами, якщо їх розпізнано. Видимість, можливість реєстрації та вікові фільтри залишаються чинними.", inherited: "Успадкована територія", selectCountry: "Спочатку виберіть країну", inactive: "неактивний", conflict: "Ці дані змінилися. Відкрийте групу повторно перед збереженням.", territoryError: "Територія не узгоджується з батьківським вузлом або підгрупами. Перевірте країну, місто та ієрархію." },
};
