import type { SupportedLocale } from "../i18n/config";

const en = {
  title: "Panel bookings", back: "Group participants", intro: "Choose a panel, then select the participants from your groups to book together.",
  panel: "Panel", choose: "Choose a panel", search: "Name or code", group: "Group", allGroups: "All groups",
  person: "Participant", seats: "Seats", status: "Status", available: "Available", selected: "Already booked", conflict: "Overlapping panel", full: "Not enough seats",
  selectAll: "Select all available participants in this view", selection: "Selected registrations", totalSeats: "Seats required", remaining: "Seats available",
  family: "Linked children are included and each occupies a seat.", submit: "Book selected participants", pending: "Booking…",
  emptyPanels: "No panels are currently available.", emptyPeople: "No participants match these filters.", clear: "Clear selection", refresh: "Refresh availability",
  confirm: "Confirm booking", review: "Review selection", cancel: "Back", atomic: "All selected registrations will be booked together. If seats or eligibility change, none will be saved.",
  success: "Registrations booked", failure: "Unable to complete the booking. No registrations were added. Refresh availability and try again.",
  scopeError: "One or more registrations are no longer available in your groups. No registrations were added.",
  fullError: "There are not enough seats for the whole selection. No registrations were added.",
  conflictError: "One or more participants already have an overlapping panel. No registrations were added.",
  unavailable: "This panel is no longer available. Choose another panel.", loadError: "Unable to load panel bookings. Please try again.",
};
export type GroupBookingCopy = { [K in keyof typeof en]: string };
export const GROUP_BOOKING_COPY: Record<SupportedLocale, GroupBookingCopy> = {
  en,
  it: {
    title: "Iscrizioni ai panel", back: "Partecipanti del gruppo", intro: "Scegli un panel, poi seleziona i partecipanti dei tuoi gruppi da iscrivere insieme.",
    panel: "Panel", choose: "Scegli un panel", search: "Nome o codice", group: "Gruppo", allGroups: "Tutti i gruppi",
    person: "Partecipante", seats: "Posti", status: "Stato", available: "Disponibile", selected: "Già iscritto", conflict: "Panel sovrapposto", full: "Posti insufficienti",
    selectAll: "Seleziona tutti i partecipanti disponibili in questa vista", selection: "Iscrizioni selezionate", totalSeats: "Posti necessari", remaining: "Posti disponibili",
    family: "I minori collegati sono inclusi e occupano un posto ciascuno.", submit: "Iscrivi i partecipanti selezionati", pending: "Iscrizione in corso…",
    emptyPanels: "Al momento non ci sono panel disponibili.", emptyPeople: "Nessun partecipante corrisponde ai filtri.", clear: "Azzera selezione", refresh: "Aggiorna disponibilità",
    confirm: "Conferma iscrizione", review: "Rivedi selezione", cancel: "Indietro", atomic: "Le iscrizioni selezionate vengono salvate insieme. Se cambiano i posti o i requisiti, nessuna viene salvata.",
    success: "Iscrizioni confermate", failure: "Non è stato possibile completare l’operazione. Nessuna iscrizione è stata aggiunta. Aggiorna la disponibilità e riprova.",
    scopeError: "Una o più iscrizioni non sono più disponibili nei tuoi gruppi. Nessuna iscrizione è stata aggiunta.",
    fullError: "I posti non bastano per l’intera selezione. Nessuna iscrizione è stata aggiunta.",
    conflictError: "Uno o più partecipanti hanno già un panel sovrapposto. Nessuna iscrizione è stata aggiunta.",
    unavailable: "Questo panel non è più disponibile. Scegli un altro panel.", loadError: "Non è stato possibile caricare le iscrizioni ai panel. Riprova.",
  },
  fr: {
    title: "Inscriptions aux panels", back: "Participants du groupe", intro: "Choisissez un panel, puis les participants de vos groupes à inscrire ensemble.",
    panel: "Panel", choose: "Choisir un panel", search: "Nom ou code", group: "Groupe", allGroups: "Tous les groupes",
    person: "Participant", seats: "Places", status: "Statut", available: "Disponible", selected: "Déjà inscrit", conflict: "Panel simultané", full: "Places insuffisantes",
    selectAll: "Sélectionner tous les participants disponibles dans cette vue", selection: "Inscriptions sélectionnées", totalSeats: "Places nécessaires", remaining: "Places disponibles",
    family: "Les mineurs associés sont inclus et occupent chacun une place.", submit: "Inscrire les participants sélectionnés", pending: "Inscription…",
    emptyPanels: "Aucun panel disponible actuellement.", emptyPeople: "Aucun participant ne correspond aux filtres.", clear: "Effacer la sélection", refresh: "Actualiser les disponibilités",
    confirm: "Confirmer l’inscription", review: "Vérifier la sélection", cancel: "Retour", atomic: "Toutes les inscriptions sont enregistrées ensemble. Si les places ou les conditions changent, aucune n’est enregistrée.",
    success: "Inscriptions confirmées", failure: "Impossible de terminer. Aucune inscription ajoutée. Actualisez les disponibilités et réessayez.",
    scopeError: "Certaines inscriptions ne sont plus disponibles dans vos groupes. Aucune inscription ajoutée.", fullError: "Les places ne suffisent pas pour toute la sélection. Aucune inscription ajoutée.",
    conflictError: "Certains participants ont déjà un panel simultané. Aucune inscription ajoutée.", unavailable: "Ce panel n’est plus disponible. Choisissez-en un autre.", loadError: "Impossible de charger les inscriptions. Réessayez.",
  },
  de: {
    title: "Panel-Anmeldungen", back: "Gruppenteilnehmer", intro: "Wähle ein Panel und dann die Teilnehmer deiner Gruppen, die du gemeinsam anmelden möchtest.",
    panel: "Panel", choose: "Panel wählen", search: "Name oder Code", group: "Gruppe", allGroups: "Alle Gruppen",
    person: "Teilnehmer", seats: "Plätze", status: "Status", available: "Verfügbar", selected: "Bereits angemeldet", conflict: "Zeitliche Überschneidung", full: "Nicht genug Plätze",
    selectAll: "Alle verfügbaren Teilnehmer dieser Ansicht auswählen", selection: "Ausgewählte Anmeldungen", totalSeats: "Benötigte Plätze", remaining: "Verfügbare Plätze",
    family: "Verknüpfte Minderjährige sind eingeschlossen und belegen jeweils einen Platz.", submit: "Ausgewählte Teilnehmer anmelden", pending: "Anmeldung läuft…",
    emptyPanels: "Derzeit sind keine Panels verfügbar.", emptyPeople: "Keine Teilnehmer entsprechen den Filtern.", clear: "Auswahl löschen", refresh: "Verfügbarkeit aktualisieren",
    confirm: "Anmeldung bestätigen", review: "Auswahl prüfen", cancel: "Zurück", atomic: "Alle Anmeldungen werden gemeinsam gespeichert. Ändern sich Plätze oder Voraussetzungen, wird keine gespeichert.",
    success: "Bestätigte Anmeldungen", failure: "Vorgang fehlgeschlagen. Keine Anmeldung hinzugefügt. Aktualisiere die Verfügbarkeit und versuche es erneut.",
    scopeError: "Einige Anmeldungen sind in deinen Gruppen nicht mehr verfügbar. Keine Anmeldung hinzugefügt.", fullError: "Für die gesamte Auswahl fehlen Plätze. Keine Anmeldung hinzugefügt.",
    conflictError: "Einige Teilnehmer haben bereits ein zeitgleiches Panel. Keine Anmeldung hinzugefügt.", unavailable: "Dieses Panel ist nicht mehr verfügbar. Wähle ein anderes.", loadError: "Anmeldungen konnten nicht geladen werden. Versuche es erneut.",
  },
  es: {
    title: "Inscripciones a paneles", back: "Participantes del grupo", intro: "Elige un panel y selecciona a los participantes de tus grupos para inscribirlos juntos.",
    panel: "Panel", choose: "Elige un panel", search: "Nombre o código", group: "Grupo", allGroups: "Todos los grupos",
    person: "Participante", seats: "Plazas", status: "Estado", available: "Disponible", selected: "Ya inscrito", conflict: "Panel simultáneo", full: "Plazas insuficientes",
    selectAll: "Seleccionar todos los participantes disponibles en esta vista", selection: "Inscripciones seleccionadas", totalSeats: "Plazas necesarias", remaining: "Plazas disponibles",
    family: "Los menores vinculados están incluidos y ocupan una plaza cada uno.", submit: "Inscribir a los participantes seleccionados", pending: "Inscribiendo…",
    emptyPanels: "No hay paneles disponibles actualmente.", emptyPeople: "Ningún participante coincide con los filtros.", clear: "Borrar selección", refresh: "Actualizar disponibilidad",
    confirm: "Confirmar inscripción", review: "Revisar selección", cancel: "Volver", atomic: "Todas las inscripciones se guardan juntas. Si cambian las plazas o los requisitos, no se guarda ninguna.",
    success: "Inscripciones confirmadas", failure: "No se pudo completar. No se añadió ninguna inscripción. Actualiza la disponibilidad e inténtalo de nuevo.",
    scopeError: "Algunas inscripciones ya no están disponibles en tus grupos. No se añadió ninguna.", fullError: "No hay plazas para toda la selección. No se añadió ninguna inscripción.",
    conflictError: "Algunos participantes ya tienen un panel simultáneo. No se añadió ninguna inscripción.", unavailable: "Este panel ya no está disponible. Elige otro.", loadError: "No se pudieron cargar las inscripciones. Inténtalo de nuevo.",
  },
  nl: {
    title: "Panelinschrijvingen", back: "Groepsdeelnemers", intro: "Kies een panel en selecteer de deelnemers uit je groepen om samen in te schrijven.",
    panel: "Panel", choose: "Kies een panel", search: "Naam of code", group: "Groep", allGroups: "Alle groepen",
    person: "Deelnemer", seats: "Plaatsen", status: "Status", available: "Beschikbaar", selected: "Al ingeschreven", conflict: "Overlappend panel", full: "Onvoldoende plaatsen",
    selectAll: "Selecteer alle beschikbare deelnemers in deze weergave", selection: "Geselecteerde inschrijvingen", totalSeats: "Benodigde plaatsen", remaining: "Beschikbare plaatsen",
    family: "Gekoppelde minderjarigen zijn inbegrepen en bezetten elk een plaats.", submit: "Geselecteerde deelnemers inschrijven", pending: "Inschrijven…",
    emptyPanels: "Er zijn momenteel geen panels beschikbaar.", emptyPeople: "Geen deelnemers voldoen aan de filters.", clear: "Selectie wissen", refresh: "Beschikbaarheid vernieuwen",
    confirm: "Inschrijving bevestigen", review: "Selectie controleren", cancel: "Terug", atomic: "Alle inschrijvingen worden samen opgeslagen. Als plaatsen of voorwaarden veranderen, wordt niets opgeslagen.",
    success: "Bevestigde inschrijvingen", failure: "De actie is mislukt. Geen inschrijvingen toegevoegd. Vernieuw de beschikbaarheid en probeer opnieuw.",
    scopeError: "Sommige inschrijvingen zijn niet meer beschikbaar in je groepen. Niets toegevoegd.", fullError: "Er zijn niet genoeg plaatsen voor de hele selectie. Niets toegevoegd.",
    conflictError: "Sommige deelnemers hebben al een overlappend panel. Niets toegevoegd.", unavailable: "Dit panel is niet meer beschikbaar. Kies een ander.", loadError: "Inschrijvingen konden niet worden geladen. Probeer opnieuw.",
  },
  uk: {
    title: "Запис на панелі", back: "Учасники групи", intro: "Оберіть панель, а потім учасників своїх груп для спільного запису.",
    panel: "Панель", choose: "Оберіть панель", search: "Ім’я або код", group: "Група", allGroups: "Усі групи",
    person: "Учасник", seats: "Місця", status: "Статус", available: "Доступно", selected: "Уже записаний", conflict: "Збіг у часі", full: "Недостатньо місць",
    selectAll: "Вибрати всіх доступних учасників у цьому списку", selection: "Вибрані реєстрації", totalSeats: "Потрібно місць", remaining: "Доступні місця",
    family: "Пов’язані неповнолітні включені, кожен займає одне місце.", submit: "Записати вибраних учасників", pending: "Запис…",
    emptyPanels: "Наразі немає доступних панелей.", emptyPeople: "Немає учасників за цими фільтрами.", clear: "Скасувати вибір", refresh: "Оновити доступність",
    confirm: "Підтвердити запис", review: "Перевірити вибір", cancel: "Назад", atomic: "Усі реєстрації зберігаються разом. Якщо місця або умови зміняться, жодну не буде збережено.",
    success: "Підтверджені реєстрації", failure: "Не вдалося завершити дію. Жодного запису не додано. Оновіть доступність і спробуйте ще раз.",
    scopeError: "Деякі реєстрації більше недоступні у ваших групах. Нічого не додано.", fullError: "Місць недостатньо для всіх вибраних. Нічого не додано.",
    conflictError: "Деякі учасники вже мають панель у цей час. Нічого не додано.", unavailable: "Ця панель більше недоступна. Оберіть іншу.", loadError: "Не вдалося завантажити записи. Спробуйте ще раз.",
  },
};
