import type { SupportedLocale } from "../i18n/config";
const en = {
  title: "Panel bookings", back: "Group participants", intro: "Choose a panel, then manage each participant’s booking.",
  panel: "Panel", choose: "Choose a panel", search: "Name or code", group: "Group", allGroups: "All groups",
  person: "Participant", seats: "Seats", status: "Status", available: "Available", selected: "Booked", conflict: "Overlapping panel", full: "Not enough seats",
  remaining: "Seats available",
  family: "Linked children are included and each occupies a seat.", pending: "Saving…",
  emptyPanels: "No panels are currently available.", emptyPeople: "No participants match these filters.", refresh: "Refresh availability", refreshHelp: "Check available seats and existing bookings again.",
  success: "Booking confirmed", failure: "Unable to complete the operation. Refresh availability and try again.",
  scopeError: "One or more registrations are no longer available in your groups. No registrations were added.",
  fullError: "There are not enough seats for this participant and their linked children.",
  conflictError: "One or more participants already have an overlapping panel. No registrations were added.",
  unavailable: "This panel is no longer available. Choose another panel.", loadError: "Unable to load panel bookings. Please try again.",
  action: "Action",
  book: "Book",
  unbook: "Cancel booking",
  notBooked: "Not booked",
  removed: "Booking cancelled",
};
export type GroupBookingCopy = { [K in keyof typeof en]: string };
export const GROUP_BOOKING_COPY: Record<SupportedLocale, GroupBookingCopy> = {
  en,
  it: {
    title: "Iscrizioni ai panel", back: "Partecipanti del gruppo", intro: "Scegli un panel e gestisci l’iscrizione di ogni partecipante.",
    panel: "Panel", choose: "Scegli un panel", search: "Nome o codice", group: "Gruppo", allGroups: "Tutti i gruppi",
    person: "Partecipante", seats: "Posti", status: "Stato", available: "Disponibile", selected: "Iscritto", conflict: "Panel sovrapposto", full: "Posti insufficienti",
    remaining: "Posti disponibili",
    family: "I minori collegati sono inclusi e occupano un posto ciascuno.", pending: "Salvataggio…",
    emptyPanels: "Al momento non ci sono panel disponibili.", emptyPeople: "Nessun partecipante corrisponde ai filtri.", refresh: "Aggiorna disponibilità", refreshHelp: "Ricontrolla i posti liberi e le iscrizioni già registrate.",
    success: "Iscrizione confermata", failure: "Non è stato possibile completare l’operazione. Aggiorna la disponibilità e riprova.",
    scopeError: "Una o più iscrizioni non sono più disponibili nei tuoi gruppi. Nessuna iscrizione è stata aggiunta.",
    fullError: "Non ci sono abbastanza posti per il partecipante e i figli collegati.",
    conflictError: "Uno o più partecipanti hanno già un panel sovrapposto. Nessuna iscrizione è stata aggiunta.",
    unavailable: "Questo panel non è più disponibile. Scegli un altro panel.", loadError: "Non è stato possibile caricare le iscrizioni ai panel. Riprova.",
  action: "Azione",
  book: "Iscrivi",
  unbook: "Disiscrivi",
  notBooked: "Non iscritto",
  removed: "Iscrizione rimossa",
  },
  fr: {
    title: "Inscriptions aux panels", back: "Participants du groupe", intro: "Choisissez un panel et gérez l’inscription de chaque participant.",
    panel: "Panel", choose: "Choisir un panel", search: "Nom ou code", group: "Groupe", allGroups: "Tous les groupes",
    person: "Participant", seats: "Places", status: "Statut", available: "Disponible", selected: "Inscrit", conflict: "Panel simultané", full: "Places insuffisantes",
    remaining: "Places disponibles",
    family: "Les mineurs associés sont inclus et occupent chacun une place.", pending: "Enregistrement…",
    emptyPanels: "Aucun panel disponible actuellement.", emptyPeople: "Aucun participant ne correspond aux filtres.", refresh: "Actualiser les disponibilités", refreshHelp: "Vérifie à nouveau les places libres et les inscriptions existantes.",
    success: "Inscription confirmée", failure: "Impossible de terminer l’opération. Actualisez les disponibilités et réessayez.",
    scopeError: "Certaines inscriptions ne sont plus disponibles dans vos groupes. Aucune inscription ajoutée.", fullError: "Il ne reste pas assez de places pour ce participant et les mineurs associés.",
    conflictError: "Certains participants ont déjà un panel simultané. Aucune inscription ajoutée.", unavailable: "Ce panel n’est plus disponible. Choisissez-en un autre.", loadError: "Impossible de charger les inscriptions. Réessayez.",
  action: "Action",
  book: "Inscrire",
  unbook: "Désinscrire",
  notBooked: "Non inscrit",
  removed: "Inscription annulée",
  },
  de: {
    title: "Panel-Anmeldungen", back: "Gruppenteilnehmer", intro: "Wähle ein Panel und verwalte die Anmeldung jedes Teilnehmers.",
    panel: "Panel", choose: "Panel wählen", search: "Name oder Code", group: "Gruppe", allGroups: "Alle Gruppen",
    person: "Teilnehmer", seats: "Plätze", status: "Status", available: "Verfügbar", selected: "Angemeldet", conflict: "Zeitliche Überschneidung", full: "Nicht genug Plätze",
    remaining: "Verfügbare Plätze",
    family: "Verknüpfte Minderjährige sind eingeschlossen und belegen jeweils einen Platz.", pending: "Speichern…",
    emptyPanels: "Derzeit sind keine Panels verfügbar.", emptyPeople: "Keine Teilnehmer entsprechen den Filtern.", refresh: "Verfügbarkeit aktualisieren", refreshHelp: "Prüft freie Plätze und bestehende Anmeldungen erneut.",
    success: "Anmeldung bestätigt", failure: "Vorgang fehlgeschlagen. Aktualisiere die Verfügbarkeit und versuche es erneut.",
    scopeError: "Einige Anmeldungen sind in deinen Gruppen nicht mehr verfügbar. Keine Anmeldung hinzugefügt.", fullError: "Für diesen Teilnehmer und die verknüpften Minderjährigen fehlen Plätze.",
    conflictError: "Einige Teilnehmer haben bereits ein zeitgleiches Panel. Keine Anmeldung hinzugefügt.", unavailable: "Dieses Panel ist nicht mehr verfügbar. Wähle ein anderes.", loadError: "Anmeldungen konnten nicht geladen werden. Versuche es erneut.",
  action: "Aktion",
  book: "Anmelden",
  unbook: "Abmelden",
  notBooked: "Nicht angemeldet",
  removed: "Anmeldung storniert",
  },
  es: {
    title: "Inscripciones a paneles", back: "Participantes del grupo", intro: "Elige un panel y gestiona la inscripción de cada participante.",
    panel: "Panel", choose: "Elige un panel", search: "Nombre o código", group: "Grupo", allGroups: "Todos los grupos",
    person: "Participante", seats: "Plazas", status: "Estado", available: "Disponible", selected: "Inscrito", conflict: "Panel simultáneo", full: "Plazas insuficientes",
    remaining: "Plazas disponibles",
    family: "Los menores vinculados están incluidos y ocupan una plaza cada uno.", pending: "Guardando…",
    emptyPanels: "No hay paneles disponibles actualmente.", emptyPeople: "Ningún participante coincide con los filtros.", refresh: "Actualizar disponibilidad", refreshHelp: "Comprueba de nuevo las plazas libres y las inscripciones existentes.",
    success: "Inscripción confirmada", failure: "No se pudo completar la operación. Actualiza la disponibilidad e inténtalo de nuevo.",
    scopeError: "Algunas inscripciones ya no están disponibles en tus grupos. No se añadió ninguna.", fullError: "No hay suficientes plazas para este participante y los menores vinculados.",
    conflictError: "Algunos participantes ya tienen un panel simultáneo. No se añadió ninguna inscripción.", unavailable: "Este panel ya no está disponible. Elige otro.", loadError: "No se pudieron cargar las inscripciones. Inténtalo de nuevo.",
  action: "Acción",
  book: "Inscribir",
  unbook: "Dar de baja",
  notBooked: "No inscrito",
  removed: "Inscripción cancelada",
  },
  nl: {
    title: "Panelinschrijvingen", back: "Groepsdeelnemers", intro: "Kies een panel en beheer de inschrijving van elke deelnemer.",
    panel: "Panel", choose: "Kies een panel", search: "Naam of code", group: "Groep", allGroups: "Alle groepen",
    person: "Deelnemer", seats: "Plaatsen", status: "Status", available: "Beschikbaar", selected: "Ingeschreven", conflict: "Overlappend panel", full: "Onvoldoende plaatsen",
    remaining: "Beschikbare plaatsen",
    family: "Gekoppelde minderjarigen zijn inbegrepen en bezetten elk een plaats.", pending: "Opslaan…",
    emptyPanels: "Er zijn momenteel geen panels beschikbaar.", emptyPeople: "Geen deelnemers voldoen aan de filters.", refresh: "Beschikbaarheid vernieuwen", refreshHelp: "Controleert vrije plaatsen en bestaande inschrijvingen opnieuw.",
    success: "Inschrijving bevestigd", failure: "De actie is mislukt. Vernieuw de beschikbaarheid en probeer opnieuw.",
    scopeError: "Sommige inschrijvingen zijn niet meer beschikbaar in je groepen. Niets toegevoegd.", fullError: "Er zijn niet genoeg plaatsen voor deze deelnemer en de gekoppelde minderjarigen.",
    conflictError: "Sommige deelnemers hebben al een overlappend panel. Niets toegevoegd.", unavailable: "Dit panel is niet meer beschikbaar. Kies een ander.", loadError: "Inschrijvingen konden niet worden geladen. Probeer opnieuw.",
  action: "Actie",
  book: "Inschrijven",
  unbook: "Uitschrijven",
  notBooked: "Niet ingeschreven",
  removed: "Inschrijving geannuleerd",
  },
  uk: {
    title: "Запис на панелі", back: "Учасники групи", intro: "Оберіть панель і керуйте записом кожного учасника.",
    panel: "Панель", choose: "Оберіть панель", search: "Ім’я або код", group: "Група", allGroups: "Усі групи",
    person: "Учасник", seats: "Місця", status: "Статус", available: "Доступно", selected: "Записаний", conflict: "Збіг у часі", full: "Недостатньо місць",
    remaining: "Доступні місця",
    family: "Пов’язані неповнолітні включені, кожен займає одне місце.", pending: "Збереження…",
    emptyPanels: "Наразі немає доступних панелей.", emptyPeople: "Немає учасників за цими фільтрами.", refresh: "Оновити доступність", refreshHelp: "Повторно перевіряє вільні місця та наявні записи.",
    success: "Запис підтверджено", failure: "Не вдалося завершити дію. Оновіть доступність і спробуйте ще раз.",
    scopeError: "Деякі реєстрації більше недоступні у ваших групах. Нічого не додано.", fullError: "Недостатньо місць для цього учасника та пов’язаних неповнолітніх.",
    conflictError: "Деякі учасники вже мають панель у цей час. Нічого не додано.", unavailable: "Ця панель більше недоступна. Оберіть іншу.", loadError: "Не вдалося завантажити записи. Спробуйте ще раз.",
  action: "Дія",
  book: "Записати",
  unbook: "Скасувати запис",
  notBooked: "Не записаний",
  removed: "Запис скасовано",
  },
};
