import type { RegistrationInput } from "@/lib/registrations/validation";

export const REGISTRATION_QUESTIONNAIRE_VERSION = "2026-06-14-first-event";

export type QuestionnaireLocale = "it" | "en";
export type QuestionDataClass = "personal" | "sensitive" | "operational" | "legal";
export type RoleVisibility =
  | "partecipante"
  | "capogruppo"
  | "manager"
  | "manager_viewer"
  | "admin"
  | "accoglienza";

export type RegistrationQuestion = {
  id: string;
  label: Record<QuestionnaireLocale, string>;
  required: boolean;
  dataClass: QuestionDataClass;
  structuredStorage: string;
  visibleTo: RoleVisibility[];
  editableAfterSubmit: boolean;
};

export const EUROPEAN_COUNTRIES = [
  "Albania",
  "Andorra",
  "Armenia",
  "Austria",
  "Azerbaigian",
  "Belgio",
  "Bielorussia",
  "Bosnia ed Erzegovina",
  "Bulgaria",
  "Cipro",
  "Croazia",
  "Danimarca",
  "Estonia",
  "Finlandia",
  "Francia",
  "Georgia",
  "Germania",
  "Grecia",
  "Irlanda",
  "Islanda",
  "Italia",
  "Kazakhstan",
  "Kosovo",
  "Lettonia",
  "Liechtenstein",
  "Lituania",
  "Lussemburgo",
  "Macedonia del Nord",
  "Malta",
  "Moldavia",
  "Monaco",
  "Montenegro",
  "Norvegia",
  "Paesi Bassi",
  "Polonia",
  "Portogallo",
  "Regno Unito",
  "Repubblica Ceca",
  "Romania",
  "Russia",
  "San Marino",
  "Serbia",
  "Slovacchia",
  "Slovenia",
  "Spagna",
  "Svezia",
  "Svizzera",
  "Turchia",
  "Ucraina",
  "Ungheria",
  "Vaticano",
] as const;

export const PLACEHOLDER_GROUPS = [
  "Gruppo della mia città",
  "Giovani per la Pace",
  "Scuola della Pace",
  "Comunità di Sant'Egidio",
  "Altro gruppo Sant'Egidio",
] as const;

export const NATIONALITY_OPTIONS = [
  "Afghan (Afghanistan)",
  "Åland Island (Åland Islands)",
  "Albanian (Albania)",
  "Algerian (Algeria)",
  "American (United States Minor Outlying Islands)",
  "American (United States of America)",
  "American Samoan (American Samoa)",
  "Andorran (Andorra)",
  "Angolan (Angola)",
  "Anguillan (Anguilla)",
  "Antarctic (Antarctica)",
  "Antiguan or Barbudan (Antigua and Barbuda)",
  "Argentine (Argentina)",
  "Armenian (Armenia)",
  "Aruban (Aruba)",
  "Australian (Australia)",
  "Austrian (Austria)",
  "Azerbaijani, Azeri (Azerbaijan)",
  "Bahamian (Bahamas)",
  "Bahraini (Bahrain)",
  "Bangladeshi (Bangladesh)",
  "Barbadian (Barbados)",
  "Barthélemois (Saint Barthélemy)",
  "Basotho (Lesotho)",
  "Belarusian (Belarus)",
  "Belgian (Belgium)",
  "Belizean (Belize)",
  "Beninese, Beninois (Benin)",
  "Bermudian, Bermudan (Bermuda)",
  "Bhutanese (Bhutan)",
  "BIOT (British Indian Ocean Territory)",
  "Bissau-Guinean (Guinea-Bissau)",
  "Bolivian (Bolivia (Plurinational State of))",
  "Bonaire (Bonaire, Sint Eustatius and Saba)",
  "Bosnian or Herzegovinian (Bosnia and Herzegovina)",
  "Bouvet Island",
  "Brazilian (Brazil)",
  "British Virgin Island (Virgin Islands (British))",
  "British, UK (United Kingdom of Great Britain and Northern Ireland)",
  "Bruneian (Brunei Darussalam)",
  "Bulgarian (Bulgaria)",
  "Burkinabé (Burkina Faso)",
  "Burmese (Myanmar)",
  "Burundian (Burundi)",
  "Cabo Verdean (Cabo Verde)",
  "Cambodian (Cambodia)",
  "Cameroonian (Cameroon)",
  "Canadian (Canada)",
  "Caymanian (Cayman Islands)",
  "Central African (Central African Republic)",
  "Chadian (Chad)",
  "Channel Island (Guernsey)",
  "Channel Island (Jersey)",
  "Chilean (Chile)",
  "Chinese (China)",
  "Chinese, Taiwanese (Taiwan, Province of China)",
  "Christmas Island",
  "Cocos Island (Cocos (Keeling) Islands)",
  "Colombian (Colombia)",
  "Comoran, Comorian (Comoros)",
  "Congolese (Congo (Democratic Republic of the))",
  "Congolese (Congo (Republic of the))",
  "Cook Island (Cook Islands)",
  "Costa Rican (Costa Rica)",
  "Croatian (Croatia)",
  "Cuban (Cuba)",
  "Curaçaoan (Curaçao)",
  "Cypriot (Cyprus)",
  "Czech (Czech Republic)",
  "Danish (Denmark)",
  "Djiboutian (Djibouti)",
  "Dominican (Dominica)",
  "Dominican (Dominican Republic)",
  "Dutch, Netherlandic (Netherlands)",
  "Ecuadorian (Ecuador)",
  "Egyptian (Egypt)",
  "Emirati, Emirian, Emiri (United Arab Emirates)",
  "Equatorial Guinean, Equatoguinean (Equatorial Guinea)",
  "Eritrean (Eritrea)",
  "Estonian (Estonia)",
  "Ethiopian (Ethiopia)",
  "Falkland Island (Falkland Islands (Malvinas))",
  "Faroese (Faroe Islands)",
  "Fijian (Fiji)",
  "Finnish (Finland)",
  "French (France)",
  "French Guianese (French Guiana)",
  "French Polynesian (French Polynesia)",
  "French Southern Territories",
  "Gabonese (Gabon)",
  "Gambian (Gambia)",
  "Georgian (Georgia)",
  "German (Germany)",
  "Ghanaian (Ghana)",
  "Gibraltar",
  "Greek, Hellenic (Greece)",
  "Greenlandic (Greenland)",
  "Grenadian (Grenada)",
  "Guadeloupe",
  "Guamanian, Guambat (Guam)",
  "Guatemalan (Guatemala)",
  "Guinean (Guinea)",
  "Guyanese (Guyana)",
  "Haitian (Haiti)",
  "Heard Island or McDonald Islands (Heard Island and McDonald Islands)",
  "Honduran (Honduras)",
  "Hong Kong, Hong Kongese (Hong Kong)",
  "Hungarian, Magyar (Hungary)",
  "I-Kiribati (Kiribati)",
  "Icelandic (Iceland)",
  "Indian (India)",
  "Indonesian (Indonesia)",
  "Iranian, Persian (Iran)",
  "Iraqi (Iraq)",
  "Irish (Ireland)",
  "Israeli (Israel)",
  "Italian (Italy)",
  "Ivorian (Côte d'Ivoire)",
  "Jamaican (Jamaica)",
  "Japanese (Japan)",
  "Jordanian (Jordan)",
  "Kazakhstani, Kazakh (Kazakhstan)",
  "Kenyan (Kenya)",
  "Kittitian or Nevisian (Saint Kitts and Nevis)",
  "Kuwaiti (Kuwait)",
  "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz (Kyrgyzstan)",
  "Lao, Laotian (Lao People's Democratic Republic)",
  "Latvian (Latvia)",
  "Lebanese (Lebanon)",
  "Liberian (Liberia)",
  "Libyan (Libya)",
  "Liechtenstein",
  "Lithuanian (Lithuania)",
  "Luxembourg, Luxembourgish (Luxembourg)",
  "Macanese, Chinese (Macao)",
  "Macedonian (Macedonia (the former Yugoslav Republic of))",
  "Mahoran (Mayotte)",
  "Malagasy (Madagascar)",
  "Malawian (Malawi)",
  "Malaysian (Malaysia)",
  "Maldivian (Maldives)",
  "Malian, Malinese (Mali)",
  "Maltese (Malta)",
  "Manx (Isle of Man)",
  "Marshallese (Marshall Islands)",
  "Martiniquais, Martinican (Martinique)",
  "Mauritanian (Mauritania)",
  "Mauritian (Mauritius)",
  "Mexican (Mexico)",
  "Micronesian (Micronesia (Federated States of))",
  "Moldovan (Moldova (Republic of))",
  "Monégasque, Monacan (Monaco)",
  "Mongolian (Mongolia)",
  "Montenegrin (Montenegro)",
  "Montserratian (Montserrat)",
  "Moroccan (Morocco)",
  "Motswana, Botswanan (Botswana)",
  "Mozambican (Mozambique)",
  "Namibian (Namibia)",
  "Nauruan (Nauru)",
  "Nepali, Nepalese (Nepal)",
  "New Caledonian (New Caledonia)",
  "New Zealand, NZ (New Zealand)",
  "Ni-Vanuatu, Vanuatuan (Vanuatu)",
  "Nicaraguan (Nicaragua)",
  "Nigerian (Nigeria)",
  "Nigerien (Niger)",
  "Niuean (Niue)",
  "Norfolk Island",
  "North Korean (Korea (Democratic People's Republic of))",
  "Northern Marianan (Northern Mariana Islands)",
  "Norwegian (Norway)",
  "Omani (Oman)",
  "Pakistani (Pakistan)",
  "Palauan (Palau)",
  "Palestinian (Palestine, State of)",
  "Panamanian (Panama)",
  "Papua New Guinean, Papuan (Papua New Guinea)",
  "Paraguayan (Paraguay)",
  "Peruvian (Peru)",
  "Philippine, Filipino (Philippines)",
  "Pitcairn Island (Pitcairn)",
  "Polish (Poland)",
  "Portuguese (Portugal)",
  "Puerto Rican (Puerto Rico)",
  "Qatari (Qatar)",
  "Réunionese, Réunionnais (Réunion)",
  "Romanian (Romania)",
  "Russian (Russian Federation)",
  "Rwandan (Rwanda)",
  "Sahrawi, Sahrawian, Sahraouian (Western Sahara)",
  "Saint Helenian (Saint Helena, Ascension and Tristan da Cunha)",
  "Saint Lucian (Saint Lucia)",
  "Saint Vincentian, Vincentian (Saint Vincent and the Grenadines)",
  "Saint-Martinoise (Saint Martin (French part))",
  "Saint-Pierrais or Miquelonnais (Saint Pierre and Miquelon)",
  "Salvadoran (El Salvador)",
  "Sammarinese (San Marino)",
  "Samoan (Samoa)",
  "São Toméan (Sao Tome and Principe)",
  "Saudi, Saudi Arabian (Saudi Arabia)",
  "Senegalese (Senegal)",
  "Serbian (Serbia)",
  "Seychellois (Seychelles)",
  "Sierra Leonean (Sierra Leone)",
  "Singaporean (Singapore)",
  "Sint Maarten (Sint Maarten (Dutch part))",
  "Slovak (Slovakia)",
  "Slovenian, Slovene (Slovenia)",
  "Solomon Island (Solomon Islands)",
  "Somali, Somalian (Somalia)",
  "South African (South Africa)",
  "South Georgia or South Sandwich Islands (South Georgia and the South Sandwich Islands)",
  "South Korean (Korea (Republic of))",
  "South Sudanese (South Sudan)",
  "Spanish (Spain)",
  "Sri Lankan (Sri Lanka)",
  "Sudanese (Sudan)",
  "Surinamese (Suriname)",
  "Svalbard (Svalbard and Jan Mayen)",
  "Swazi (Swaziland)",
  "Swedish (Sweden)",
  "Swiss (Switzerland)",
  "Syrian (Syrian Arab Republic)",
  "Tajikistani (Tajikistan)",
  "Tanzanian (Tanzania, United Republic of)",
  "Thai (Thailand)",
  "Timorese (Timor-Leste)",
  "Togolese (Togo)",
  "Tokelauan (Tokelau)",
  "Tongan (Tonga)",
  "Trinidadian or Tobagonian (Trinidad and Tobago)",
  "Tunisian (Tunisia)",
  "Turkish (Turkey)",
  "Turkmen (Turkmenistan)",
  "Turks and Caicos Island (Turks and Caicos Islands)",
  "Tuvaluan (Tuvalu)",
  "U.S. Virgin Island (Virgin Islands (U.S.))",
  "Ugandan (Uganda)",
  "Ukrainian (Ukraine)",
  "Uruguayan (Uruguay)",
  "Uzbekistani, Uzbek (Uzbekistan)",
  "Vatican (Vatican City State)",
  "Venezuelan (Venezuela (Bolivarian Republic of))",
  "Vietnamese (Vietnam)",
  "Wallis and Futuna, Wallisian or Futunan (Wallis and Futuna)",
  "Yemeni (Yemen)",
  "Zambian (Zambia)",
  "Zimbabwean (Zimbabwe)",
] as const;

export const EUROPEAN_CITY_OPTIONS: Record<string, readonly string[]> = {
  Albania: ["Tirana", "Durazzo", "Valona", "Scutari", "Elbasan", "Korça"],
  Andorra: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana"],
  Armenia: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
  Austria: ["Vienna", "Graz", "Linz", "Salisburgo", "Innsbruck", "Klagenfurt"],
  Azerbaigian: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Shirvan"],
  Belgio: ["Bruxelles", "Anversa", "Gand", "Charleroi", "Liegi", "Bruges", "Namur"],
  Bielorussia: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"],
  "Bosnia ed Erzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora"],
  Cipro: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagosta"],
  Croazia: ["Zagabria", "Spalato", "Fiume", "Osijek", "Zara", "Pola"],
  Danimarca: ["Copenaghen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Estonia: ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Jarve"],
  Finlandia: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku"],
  Francia: ["Parigi", "Marsiglia", "Lione", "Tolosa", "Nizza", "Nantes", "Strasburgo", "Montpellier", "Bordeaux", "Lille"],
  Georgia: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  Germania: [
    "Berlino",
    "Amburgo",
    "Monaco di Baviera",
    "Colonia",
    "Francoforte",
    "Stoccarda",
    "Dusseldorf",
    "Dortmund",
    "Essen",
    "Lipsia",
    "Brema",
    "Dresda",
    "Hannover",
    "Norimberga",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle (Saale)",
    "Magdeburgo",
    "Friburgo in Brisgovia",
    "Krefeld",
    "Magonza",
    "Lubecca",
    "Erfurt",
    "Rostock",
    "Kassel",
    "Potsdam",
    "Saarbrücken",
    "Schwerin",
    "Würzburg",
  ],
  Grecia: ["Atene", "Salonicco", "Patrasso", "Heraklion", "Larissa", "Volos"],
  Irlanda: ["Dublino", "Cork", "Galway", "Limerick", "Waterford"],
  Islanda: ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Reykjanesbaer"],
  Italia: [
    "Agrigento", "Alessandria", "Ancona", "Aosta", "Arezzo", "Ascoli Piceno", "Asti", "Avellino", "Bari", "Barletta", "Belluno", "Benevento", "Bergamo", "Biella", "Bologna", "Bolzano", "Brescia", "Brindisi", "Cagliari", "Caltanissetta", "Campobasso", "Carbonia", "Caserta", "Catania", "Catanzaro", "Chieti", "Como", "Cosenza", "Cremona", "Crotone", "Cuneo", "Enna", "Fermo", "Ferrara", "Firenze", "Foggia", "Forli", "Frosinone", "Genova", "Gorizia", "Grosseto", "Imperia", "Isernia", "L'Aquila", "La Spezia", "Latina", "Lecce", "Lecco", "Livorno", "Lodi", "Lucca", "Macerata", "Mantova", "Massa", "Matera", "Messina", "Milano", "Modena", "Monza", "Napoli", "Novara", "Nuoro", "Oristano", "Padova", "Palermo", "Parma", "Pavia", "Perugia", "Pesaro", "Pescara", "Piacenza", "Pisa", "Pistoia", "Pordenone", "Potenza", "Prato", "Ragusa", "Ravenna", "Reggio Calabria", "Reggio Emilia", "Rieti", "Rimini", "Roma", "Rovigo", "Salerno", "Sassari", "Savona", "Siena", "Siracusa", "Sondrio", "Taranto", "Teramo", "Terni", "Torino", "Trapani", "Trento", "Treviso", "Trieste", "Udine", "Varese", "Venezia", "Verbano-Cusio-Ossola", "Vercelli", "Verona", "Vibo Valentia", "Vicenza", "Viterbo"
  ],
  Kazakhstan: ["Astana", "Almaty", "Shymkent", "Karaganda", "Aktobe", "Atyrau"],
  Kosovo: ["Pristina", "Prizren", "Peja", "Gjilan", "Mitrovica", "Gjakova"],
  Lettonia: ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala"],
  Liechtenstein: ["Vaduz", "Schaan", "Triesen", "Balzers"],
  Lituania: ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys"],
  Lussemburgo: ["Lussemburgo", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  "Macedonia del Nord": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid"],
  Malta: ["La Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema"],
  Moldavia: ["Chisinau", "Balti", "Tiraspol", "Bender", "Cahul"],
  Monaco: ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"],
  Montenegro: ["Podgorica", "Niksic", "Herceg Novi", "Pljevlja", "Budva"],
  Norvegia: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Tromso"],
  "Paesi Bassi": ["Amsterdam", "Rotterdam", "L'Aia", "Utrecht", "Eindhoven", "Groningen"],
  Polonia: ["Varsavia", "Cracovia", "Lodz", "Breslavia", "Poznan", "Danzica", "Stettino", "Lublino"],
  Portogallo: ["Lisbona", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Coimbra", "Funchal"],
  "Regno Unito": ["Londra", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Leeds", "Edimburgo", "Bristol", "Cardiff", "Belfast"],
  "Repubblica Ceca": ["Praga", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc"],
  Romania: ["Bucarest", "Cluj-Napoca", "Timisoara", "Iasi", "Costanza", "Craiova", "Brasov"],
  Russia: ["Mosca", "San Pietroburgo", "Novosibirsk", "Ekaterinburg", "Kazan", "Nizhny Novgorod", "Samara", "Rostov sul Don"],
  "San Marino": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"],
  Serbia: ["Belgrado", "Novi Sad", "Nis", "Kragujevac", "Subotica"],
  Slovacchia: ["Bratislava", "Kosice", "Presov", "Zilina", "Nitra"],
  Slovenia: ["Lubiana", "Maribor", "Celje", "Kranj", "Capodistria"],
  Spagna: ["Madrid", "Barcellona", "Valencia", "Siviglia", "Saragozza", "Malaga", "Murcia", "Palma di Maiorca", "Bilbao"],
  Svezia: ["Stoccolma", "Goteborg", "Malmo", "Uppsala", "Vasteras", "Orebro"],
  Svizzera: ["Zurigo", "Ginevra", "Basilea", "Losanna", "Berna", "Lucerna", "Lugano"],
  Turchia: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep"],
  Ucraina: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Leopoli", "Zaporizhzhia"],
  Ungheria: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor"],
  Vaticano: ["Città del Vaticano"],
};

export const ACCESSIBILITY_DIFFICULTIES = [
  {
    key: "seeing",
    label: {
      it: "Vedere, anche usando occhiali",
      en: "Seeing, even when wearing glasses",
    },
  },
  {
    key: "hearing",
    label: {
      it: "Sentire, anche usando apparecchi acustici",
      en: "Hearing, even when using a hearing aid",
    },
  },
  {
    key: "walkingOrSteps",
    label: {
      it: "Camminare o salire gradini",
      en: "Walking or climbing steps",
    },
  },
  {
    key: "selfCare",
    label: {
      it: "Prendersi cura di sé, per esempio lavarsi o vestirsi",
      en: "Self-care, such as washing or dressing",
    },
  },
  {
    key: "rememberingOrConcentrating",
    label: {
      it: "Ricordare o concentrarsi",
      en: "Remembering or concentrating",
    },
  },
  {
    key: "communicating",
    label: {
      it: "Comunicare, capire o farsi capire dalle altre persone",
      en: "Communicating in your usual language",
    },
  },
  {
    key: "wheelchairOrMobilityAid",
    label: {
      it: "Uso di sedia a rotelle o altro ausilio per la mobilita'",
      en: "Use of a wheelchair or another mobility aid",
    },
  },
  {
    key: "eventAssistance",
    label: {
      it: "Bisogno di assistenza durante l'evento",
      en: "Need for assistance during the event",
    },
  },
] as const;

export const REGISTRATION_QUESTIONS: RegistrationQuestion[] = [
  {
    id: "email",
    label: { it: "Email", en: "Email" },
    required: true,
    dataClass: "personal",
    structuredStorage: "participant_contacts.email",
    visibleTo: ["partecipante", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: false,
  },
  {
    id: "phone",
    label: { it: "Telefono (opzionale)", en: "Phone (optional)" },
    required: false,
    dataClass: "personal",
    structuredStorage: "participant_contacts.phone",
    visibleTo: ["partecipante", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "identity",
    label: { it: "Nome, cognome e data di nascita", en: "First name, last name and date of birth" },
    required: true,
    dataClass: "personal",
    structuredStorage: "participants.first_name,last_name,birth_date",
    visibleTo: ["partecipante", "capogruppo", "manager", "manager_viewer", "admin", "accoglienza"],
    editableAfterSubmit: true,
  },
  {
    id: "preferred_locale",
    label: { it: "Lingua preferita", en: "Preferred language" },
    required: true,
    dataClass: "operational",
    structuredStorage: "participants.preferred_locale",
    visibleTo: ["partecipante", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "place",
    label: { it: "Paese e città", en: "Country and city" },
    required: true,
    dataClass: "personal",
    structuredStorage: "participants.country_other,city_other",
    visibleTo: ["partecipante", "capogruppo", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "previous_santegidio_participation",
    label: {
      it: "Hai già partecipato a eventi o iniziative Sant'Egidio?",
      en: "Have you already joined Sant'Egidio events or initiatives?",
    },
    required: false,
    dataClass: "operational",
    structuredStorage: "participants.has_previous_santegidio_participation",
    visibleTo: ["partecipante", "capogruppo", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "group_participation",
    label: {
      it: "Partecipi con un gruppo Sant'Egidio?",
      en: "Are you joining with a Sant'Egidio group?",
    },
    required: false,
    dataClass: "operational",
    structuredStorage: "participants.participates_with_group,participant_group_assignments",
    visibleTo: ["partecipante", "capogruppo", "manager", "manager_viewer", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "attendance",
    label: {
      it: "Partecipazione prevista e momenti del programma",
      en: "Expected attendance and programme moments",
    },
    required: false,
    dataClass: "operational",
    structuredStorage: "event_attendance_choices,moment_attendance_choices",
    visibleTo: ["partecipante", "capogruppo", "manager", "manager_viewer", "admin", "accoglienza"],
    editableAfterSubmit: true,
  },
  {
    id: "washington_group_accessibility",
    label: { it: "Disabilità o bisogni di accessibilità", en: "Disability or accessibility needs" },
    required: true,
    dataClass: "sensitive",
    structuredStorage: "accessibility_needs.washington_group_answers",
    visibleTo: ["partecipante", "manager", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "accessibility_support",
    label: {
      it: "Richiesta di supporto operativo e note",
      en: "Operational support request and notes",
    },
    required: false,
    dataClass: "sensitive",
    structuredStorage: "accessibility_needs.needs_operational_support,operational_notes",
    visibleTo: ["partecipante", "manager", "admin"],
    editableAfterSubmit: true,
  },
  {
    id: "privacy_consents",
    label: { it: "Privacy e consenso trattamento dati", en: "Privacy and data processing consent" },
    required: true,
    dataClass: "legal",
    structuredStorage: "participant_consents",
    visibleTo: ["partecipante", "manager", "admin"],
    editableAfterSubmit: false,
  },
];

export function getQuestionnaireVisibilitySummary() {
  return Object.fromEntries(
    REGISTRATION_QUESTIONS.map((question) => [
      question.id,
      {
        dataClass: question.dataClass,
        visibleTo: question.visibleTo,
        editableAfterSubmit: question.editableAfterSubmit,
      },
    ])
  );
}

export function buildRegistrationQuestionnaireAnswers(input: RegistrationInput) {
  return {
    birthPlace: input.birthPlace,
    nationality: input.nationality,
    phone: input.phone,
    previousSantegidioParticipation: input.hasPreviousSantegidioParticipation,
    groupParticipation: {
      participatesWithGroup: input.participatesWithGroup,
      selectedGroupId: input.groupId,
      selectedGroupName: input.groupName,
    },
    attendance: {
      overallChoice: input.attendanceChoice,
      availabilityDays: input.availabilityDays,
      availabilityUnknown: input.availabilityUnknown,
      moments: input.momentAttendanceChoices,
    },
    accessibility: {
      hasAccessibilityNeeds: input.hasAccessibilityNeeds,
      washingtonGroupAnswers: input.accessibilityAnswers,
      needsOperationalSupport: input.needsOperationalSupport,
      hasNotes: Boolean(input.accessibilityNotes),
    },
    consents: {
      privacyAccepted: input.privacyAccepted,
      dataProcessingAccepted: input.dataProcessingAccepted,
    },
  };
}
