import type { SupportedLocale } from "../i18n/config.ts";
export const BIRTH_DATE_COPY: Record<SupportedLocale, { warning: string; confirm: string }> = {
  it: { warning: "Questa data indica meno di un anno di età. Controlla soprattutto l’anno di nascita. Se stai aggiungendo un bambino accompagnato, usa la sezione figli nell’iscrizione del genitore.", confirm: "Ho verificato la data: il partecipante ha davvero meno di un anno." },
  en: { warning: "This date indicates an age under one year. Check the birth year carefully. For an accompanying child, use the children section in the parent's registration.", confirm: "I have checked the date: this participant really is under one year old." },
  fr: { warning: "Cette date indique un âge inférieur à un an. Vérifiez surtout l’année de naissance. Pour un enfant accompagné, utilisez la rubrique enfants dans l’inscription du parent.", confirm: "J’ai vérifié la date : ce participant a bien moins d’un an." },
  de: { warning: "Dieses Datum ergibt ein Alter unter einem Jahr. Prüfen Sie besonders das Geburtsjahr. Nutzen Sie für ein begleitetes Kind den Kinderbereich in der Anmeldung des Elternteils.", confirm: "Ich habe das Datum geprüft: Diese Person ist tatsächlich unter einem Jahr alt." },
  es: { warning: "Esta fecha indica una edad inferior a un año. Revisa especialmente el año de nacimiento. Para un niño acompañado, utiliza la sección de hijos en la inscripción del progenitor.", confirm: "He comprobado la fecha: esta persona tiene realmente menos de un año." },
  nl: { warning: "Deze datum geeft een leeftijd van minder dan één jaar aan. Controleer vooral het geboortejaar. Gebruik voor een begeleid kind het onderdeel kinderen in de inschrijving van de ouder.", confirm: "Ik heb de datum gecontroleerd: deze deelnemer is echt jonger dan één jaar." },
  uk: { warning: "Ця дата означає вік до одного року. Уважно перевірте рік народження. Для дитини в супроводі дорослого скористайтеся розділом дітей у реєстрації одного з батьків.", confirm: "Я перевірив/перевірила дату: цьому учаснику справді менше одного року." },
};
