import type { SupportedLocale } from "../i18n/config.ts";

const en = { personalEmailRequired: "Save a personal email in the contact details before choosing direct delivery.", delegateEmailRequired: "Your account has no email for delegated delivery.",
  personalEmail: "Personal email (optional)", delivery: "Communication delivery", personal: "Send to the participant’s personal email",
  delegated: "Deliver to me as group leader", responsible: "Responsible group leader", save: "Save", qr: "Participant QR code",
  code: "Personal code", download: "Download QR", unavailable: "QR unavailable", active: "QR active", inactive: "QR inactive",
  attendance: "Expected attendance", unknown: "To be confirmed", morning: "Morning", afternoon: "Afternoon", status: "Registration status",
  submitted: "Registered", confirmed: "Confirmed", cancelled: "Cancelled", draft: "Draft", group: "Group", service: "Service",
  help: "Personal email and phone are optional. With delegated delivery, communications go to your email. Without a personal email, no personal account or sign-in link is created. A personal email can be added to this same registration later.",
  deliveryHelp: "Saving makes you the responsible contact. Delegated delivery uses your account email and keeps the participant’s personal email separate.",
  missing: "Not provided", invalidDelegate: "The previous contact is no longer authorized. Choose a delivery option again.",
  linkedEmail: "This email is linked to a personal account. The participant must change it through their account.",
};
export type ManagedParticipantCopy = typeof en;
export const MANAGED_PARTICIPANT_COPY: Record<SupportedLocale, ManagedParticipantCopy> = {
 en,
 it: { personalEmailRequired: "Salva prima un’email personale nei contatti, poi scegli la consegna diretta.", delegateEmailRequired: "Il tuo account non ha un’email per la consegna delegata.", personalEmail: "Email personale (facoltativa)", delivery: "Recapito delle comunicazioni", personal: "Invia all’email personale del partecipante", delegated: "Consegna a me come capogruppo", responsible: "Capogruppo responsabile", save: "Salva", qr: "QR code del partecipante", code: "Codice personale", download: "Scarica QR", unavailable: "QR non disponibile", active: "QR attivo", inactive: "QR non attivo", attendance: "Presenze previste", unknown: "Da confermare", morning: "Mattina", afternoon: "Pomeriggio", status: "Stato iscrizione", submitted: "Iscritto", confirmed: "Confermato", cancelled: "Annullata", draft: "Bozza", group: "Gruppo", service: "Servizio", help: "Email personale e telefono sono facoltativi. Con il recapito delegato le comunicazioni arrivano alla tua email. Senza email personale non vengono creati un account o un link di accesso. Potrai aggiungere un’email personale alla stessa iscrizione in seguito.", deliveryHelp: "Salvando diventi il referente responsabile. La consegna delegata usa l’email del tuo account e mantiene separata l’email personale del partecipante.", missing: "Non indicato", invalidDelegate: "Il precedente referente non è più autorizzato. Scegli nuovamente il recapito.", linkedEmail: "Questa email è collegata a un account personale. Deve modificarla il partecipante tramite il proprio account." },
 fr: { personalEmailRequired: "Enregistrez d’abord un e-mail personnel dans les coordonnées, puis choisissez l’envoi direct.", delegateEmailRequired: "Votre compte n’a pas d’e-mail pour la remise déléguée.", personalEmail: "E-mail personnel (facultatif)", delivery: "Envoi des communications", personal: "Envoyer à l’e-mail personnel du participant", delegated: "Me remettre les messages en tant que responsable", responsible: "Responsable du groupe", save: "Enregistrer", qr: "Code QR du participant", code: "Code personnel", download: "Télécharger le QR", unavailable: "QR indisponible", active: "QR actif", inactive: "QR inactif", attendance: "Présences prévues", unknown: "À confirmer", morning: "Matin", afternoon: "Après-midi", status: "Statut de l’inscription", submitted: "Inscrit", confirmed: "Confirmé", cancelled: "Annulée", draft: "Brouillon", group: "Groupe", service: "Service", help: "L’e-mail personnel et le téléphone sont facultatifs. Les communications déléguées arrivent à votre e-mail. Sans e-mail personnel, aucun compte ni lien de connexion n’est créé. Un e-mail personnel pourra être ajouté à cette même inscription.", deliveryHelp: "En enregistrant, vous devenez le contact responsable. L’envoi délégué utilise l’e-mail de votre compte et le conserve séparé de l’e-mail personnel du participant.", missing: "Non renseigné", invalidDelegate: "Le contact précédent n’est plus autorisé. Choisissez à nouveau le destinataire des communications.", linkedEmail: "Cet e-mail est lié à un compte personnel. Le participant doit le modifier depuis son compte." },
 de: { personalEmailRequired: "Speichern Sie zuerst eine persönliche E-Mail in den Kontaktdaten und wählen Sie dann die direkte Zustellung.", delegateEmailRequired: "Ihr Konto hat keine E-Mail für die delegierte Zustellung.", personalEmail: "Persönliche E-Mail (optional)", delivery: "Zustellung von Mitteilungen", personal: "An die persönliche E-Mail des Teilnehmers senden", delegated: "An mich als Gruppenleitung zustellen", responsible: "Verantwortliche Gruppenleitung", save: "Speichern", qr: "QR-Code des Teilnehmers", code: "Persönlicher Code", download: "QR herunterladen", unavailable: "QR nicht verfügbar", active: "QR aktiv", inactive: "QR inaktiv", attendance: "Geplante Anwesenheit", unknown: "Noch zu bestätigen", morning: "Vormittag", afternoon: "Nachmittag", status: "Anmeldestatus", submitted: "Angemeldet", confirmed: "Bestätigt", cancelled: "Storniert", draft: "Entwurf", group: "Gruppe", service: "Dienst", help: "Persönliche E-Mail und Telefon sind optional. Bei delegierter Zustellung gehen Mitteilungen an Ihre E-Mail. Ohne persönliche E-Mail werden weder Konto noch Anmeldelink erstellt. Eine persönliche E-Mail kann später zur selben Anmeldung hinzugefügt werden.", deliveryHelp: "Mit dem Speichern werden Sie zur verantwortlichen Kontaktperson. Die delegierte Zustellung verwendet Ihre Konto-E-Mail und hält sie von der persönlichen E-Mail des Teilnehmers getrennt.", missing: "Nicht angegeben", invalidDelegate: "Die bisherige Kontaktperson ist nicht mehr berechtigt. Wählen Sie die Zustellung erneut.", linkedEmail: "Diese E-Mail ist mit einem persönlichen Konto verknüpft. Der Teilnehmer muss sie über sein Konto ändern." },
 es: { personalEmailRequired: "Guarda primero un correo personal en los contactos y después elige la entrega directa.", delegateEmailRequired: "Tu cuenta no tiene correo para la entrega delegada.", personalEmail: "Correo personal (opcional)", delivery: "Entrega de comunicaciones", personal: "Enviar al correo personal del participante", delegated: "Entregarme los mensajes como responsable", responsible: "Responsable del grupo", save: "Guardar", qr: "Código QR del participante", code: "Código personal", download: "Descargar QR", unavailable: "QR no disponible", active: "QR activo", inactive: "QR inactivo", attendance: "Asistencia prevista", unknown: "Por confirmar", morning: "Mañana", afternoon: "Tarde", status: "Estado de la inscripción", submitted: "Inscrito", confirmed: "Confirmado", cancelled: "Cancelada", draft: "Borrador", group: "Grupo", service: "Servicio", help: "El correo personal y el teléfono son opcionales. Las comunicaciones delegadas llegan a tu correo. Sin correo personal no se crean una cuenta ni un enlace de acceso. Podrás añadir un correo personal a esta misma inscripción más adelante.", deliveryHelp: "Al guardar, te conviertes en el contacto responsable. La entrega delegada utiliza el correo de tu cuenta y lo mantiene separado del correo personal del participante.", missing: "No indicado", invalidDelegate: "El contacto anterior ya no está autorizado. Vuelve a elegir la entrega.", linkedEmail: "Este correo está vinculado a una cuenta personal. El participante debe cambiarlo desde su cuenta." },
 nl: { personalEmailRequired: "Sla eerst een persoonlijke e-mail op bij de contactgegevens en kies daarna directe bezorging.", delegateEmailRequired: "Je account heeft geen e-mail voor gedelegeerde bezorging.", personalEmail: "Persoonlijke e-mail (optioneel)", delivery: "Bezorging van berichten", personal: "Versturen naar de persoonlijke e-mail van de deelnemer", delegated: "Aan mij bezorgen als groepsleider", responsible: "Verantwoordelijke groepsleider", save: "Opslaan", qr: "QR-code van de deelnemer", code: "Persoonlijke code", download: "QR downloaden", unavailable: "QR niet beschikbaar", active: "QR actief", inactive: "QR inactief", attendance: "Verwachte aanwezigheid", unknown: "Nog te bevestigen", morning: "Ochtend", afternoon: "Middag", status: "Inschrijvingsstatus", submitted: "Ingeschreven", confirmed: "Bevestigd", cancelled: "Geannuleerd", draft: "Concept", group: "Groep", service: "Dienst", help: "Persoonlijke e-mail en telefoon zijn optioneel. Gedelegeerde berichten komen op jouw e-mail aan. Zonder persoonlijke e-mail wordt geen account of inloglink aangemaakt. Later kan een persoonlijke e-mail aan dezelfde inschrijving worden toegevoegd.", deliveryHelp: "Door op te slaan word je de verantwoordelijke contactpersoon. Gedelegeerde bezorging gebruikt de e-mail van je account en houdt deze gescheiden van de persoonlijke e-mail van de deelnemer.", missing: "Niet opgegeven", invalidDelegate: "De vorige contactpersoon is niet meer bevoegd. Kies de bezorging opnieuw.", linkedEmail: "Deze e-mail is gekoppeld aan een persoonlijk account. De deelnemer moet deze via het eigen account wijzigen." },
 uk: { personalEmailRequired: "Спочатку збережіть особисту пошту в контактах, потім виберіть пряму доставку.", delegateEmailRequired: "У вашому обліковому записі немає пошти для делегованої доставки.", personalEmail: "Особиста електронна пошта (необов’язково)", delivery: "Доставка повідомлень", personal: "Надсилати на особисту пошту учасника", delegated: "Доставляти мені як керівнику групи", responsible: "Відповідальний керівник групи", save: "Зберегти", qr: "QR-код учасника", code: "Особистий код", download: "Завантажити QR", unavailable: "QR недоступний", active: "QR активний", inactive: "QR неактивний", attendance: "Очікувана присутність", unknown: "Буде підтверджено", morning: "Ранок", afternoon: "Друга половина дня", status: "Статус реєстрації", submitted: "Зареєстровано", confirmed: "Підтверджено", cancelled: "Скасовано", draft: "Чернетка", group: "Група", service: "Служба", help: "Особиста пошта й телефон необов’язкові. Делеговані повідомлення надходять на вашу пошту. Без особистої пошти обліковий запис і посилання для входу не створюються. Особисту пошту можна додати до цієї самої реєстрації пізніше.", deliveryHelp: "Після збереження ви стаєте відповідальною контактною особою. Делегована доставка використовує пошту вашого облікового запису та зберігає її окремо від особистої пошти учасника.", missing: "Не вказано", invalidDelegate: "Попередня контактна особа більше не має дозволу. Виберіть доставку знову.", linkedEmail: "Цю пошту пов’язано з особистим обліковим записом. Учасник має змінити її через свій обліковий запис." },
};
