import type { SupportedLocale } from "../i18n/config";
// title, save, saved, loading, load error, retry, add child, child added, help
export const OPERATIONAL_ADDITIONS_COPY: Record<SupportedLocale, readonly string[]> = {
 it: ["Accessibilità e percorsi facilitati", "Salva accessibilità", "Accessibilità aggiornata.", "Caricamento…", "Impossibile caricare i dati di accessibilità.", "Riprova", "Aggiungi figlio", "Figlio aggiunto all’iscrizione.", "Seleziona i bisogni comunicati dalla persona. Deseleziona un’opzione per rimuoverla."],
 en: ["Accessibility and accessible routes", "Save accessibility", "Accessibility updated.", "Loading…", "Unable to load accessibility details.", "Try again", "Add child", "Child added to the registration.", "Select the needs reported by the person. Uncheck an option to remove it."],
 fr: ["Accessibilité et parcours adaptés", "Enregistrer l’accessibilité", "Accessibilité mise à jour.", "Chargement…", "Impossible de charger les informations d’accessibilité.", "Réessayer", "Ajouter un enfant", "Enfant ajouté à l’inscription.", "Sélectionnez les besoins communiqués par la personne. Décochez une option pour la supprimer."],
 de: ["Barrierefreiheit und barrierefreie Wege", "Barrierefreiheit speichern", "Barrierefreiheit aktualisiert.", "Wird geladen…", "Angaben zur Barrierefreiheit konnten nicht geladen werden.", "Erneut versuchen", "Kind hinzufügen", "Kind zur Anmeldung hinzugefügt.", "Wähle die von der Person mitgeteilten Bedürfnisse aus. Entferne das Häkchen, um eine Option zu löschen."],
 es: ["Accesibilidad y recorridos adaptados", "Guardar accesibilidad", "Accesibilidad actualizada.", "Cargando…", "No se pudieron cargar los datos de accesibilidad.", "Reintentar", "Añadir hijo", "Hijo añadido a la inscripción.", "Selecciona las necesidades comunicadas por la persona. Desmarca una opción para eliminarla."],
 nl: ["Toegankelijkheid en toegankelijke routes", "Toegankelijkheid opslaan", "Toegankelijkheid bijgewerkt.", "Laden…", "De toegankelijkheidsgegevens konden niet worden geladen.", "Opnieuw proberen", "Kind toevoegen", "Kind toegevoegd aan de inschrijving.", "Selecteer de behoeften die de persoon heeft doorgegeven. Vink een optie uit om deze te verwijderen."],
 uk: ["Доступність та доступні маршрути", "Зберегти доступність", "Дані про доступність оновлено.", "Завантаження…", "Не вдалося завантажити дані про доступність.", "Спробувати ще раз", "Додати дитину", "Дитину додано до реєстрації.", "Виберіть потреби, про які повідомила людина. Зніміть позначку, щоб видалити варіант."],
};
