export const OTHER_PHONE_PREFIX = "other";

export const PHONE_PREFIX_OPTIONS = [
  { country: "IT", value: "+39", label: "Italia +39" },
  { country: "FR", value: "+33", label: "Francia +33" },
  { country: "DE", value: "+49", label: "Germania +49" },
  { country: "ES", value: "+34", label: "Spagna +34" },
  { country: "PT", value: "+351", label: "Portogallo +351" },
  { country: "GB", value: "+44", label: "Regno Unito +44" },
  { country: "IE", value: "+353", label: "Irlanda +353" },
  { country: "CH", value: "+41", label: "Svizzera +41" },
  { country: "AT", value: "+43", label: "Austria +43" },
  { country: "BE", value: "+32", label: "Belgio +32" },
  { country: "NL", value: "+31", label: "Paesi Bassi +31" },
  { country: "DK", value: "+45", label: "Danimarca +45" },
  { country: "SE", value: "+46", label: "Svezia +46" },
  { country: "NO", value: "+47", label: "Norvegia +47" },
  { country: "FI", value: "+358", label: "Finlandia +358" },
  { country: "PL", value: "+48", label: "Polonia +48" },
  { country: "CZ", value: "+420", label: "Cechia +420" },
  { country: "SK", value: "+421", label: "Slovacchia +421" },
  { country: "HU", value: "+36", label: "Ungheria +36" },
  { country: "SI", value: "+386", label: "Slovenia +386" },
  { country: "HR", value: "+385", label: "Croazia +385" },
  { country: "GR", value: "+30", label: "Grecia +30" },
  { country: "RO", value: "+40", label: "Romania +40" },
  { country: "BG", value: "+359", label: "Bulgaria +359" },
  { country: "UA", value: "+380", label: "Ucraina +380" },
  { country: "US", value: "+1", label: "Stati Uniti / Canada +1" },
  { country: "BR", value: "+55", label: "Brasile +55" },
  { country: "AR", value: "+54", label: "Argentina +54" },
  { country: "MX", value: "+52", label: "Messico +52" },
  { country: "IN", value: "+91", label: "India +91" },
  { country: "CN", value: "+86", label: "Cina +86" },
  { country: "JP", value: "+81", label: "Giappone +81" },
  { country: "AU", value: "+61", label: "Australia +61" },
  { country: "MA", value: "+212", label: "Marocco +212" },
  { country: "TN", value: "+216", label: "Tunisia +216" },
  { country: "EG", value: "+20", label: "Egitto +20" },
] as const;
